# Generated By: Claude Code (Claude Opus 4.6)

.PHONY: check help install install-dev install-no-deps uninstall clean format install-pipx uninstall-pipx

PACKAGE_NAME ?= agent_service
PROJECT_NAME ?= agent-service
VERSION_FILE := agent_service/__init__.py
VERSION_DIRS := agent_service

# Interpreter used to bootstrap the venv. CI should override with PY_SYS=python
# so the venv pins to the setup-python matrix interpreter.
PY_SYS ?= python3

ifeq ($(OS),Windows_NT)
	VENV_DIR ?= .venv
	PYTHON ?= $(VENV_DIR)/Scripts/python.exe
else
	VENV_DIR ?= .venv
	PYTHON ?= $(VENV_DIR)/bin/python
endif

# Subsystem fragments. Included AFTER PYTHON/PY_SYS are defined so prereq
# expansion in those fragments resolves correctly.
-include make/service.mk
-include make/test.mk
-include make/version-check.mk

$(info venv: $(VENV_DIR))

check: test-format test-lint test-typecheck test-unit test-coverage test-reachability version-check  ## Run read-only quality gate (default). test-complexity and test-mutation are opt-in.

.DEFAULT_GOAL := check

help:  ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

$(PYTHON):
	$(PY_SYS) -m venv $(VENV_DIR)

install: $(PYTHON)  ## Install package
	$(PYTHON) -m pip install .

install-dev: $(PYTHON)  ## Install in editable mode with dev deps
	$(PYTHON) -m pip install -e ".[dev]"

install-no-deps: $(PYTHON)  ## Install in editable mode without dependencies
	$(PYTHON) -m pip install -e . --no-deps

uninstall: $(PYTHON)  ## Uninstall package
	$(PYTHON) -m pip uninstall -y $(PACKAGE_NAME)

install-pipx:  ## Install globally via pipx
	python3 -m pipx install . --force

uninstall-pipx:  ## Uninstall the pipx install
	python3 -m pipx uninstall $(PROJECT_NAME)

clean:  ## Remove build artifacts and caches
	rm -rf build/ dist/ *.egg-info
	find . -type d -name __pycache__ -exec rm -r {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true

format: install-dev  ## Format code with black (mutating; not part of check)
	$(PYTHON) -m black $(PACKAGE_NAME) tests
