# Generated By: Claude Code (Claude Opus 4.6)

"""Shared fixtures and safety guards for tests."""

import builtins
import multiprocessing
import shutil
import subprocess
import urllib.request
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

# mutmut 2.x workaround for Python 3.13+
_orig_set_start_method = multiprocessing.set_start_method


def _patched_set_start_method(method, force=False):
    _orig_set_start_method(method, force=True)


multiprocessing.set_start_method = _patched_set_start_method

_PROJECT_ROOT = Path(__file__).resolve().parent.parent


@pytest.fixture(autouse=True)
def _block_subprocess():
    """Block subprocess globally — no real commands in tests."""

    def _blocked(*args, **kwargs):
        cmd = args[0] if args else kwargs.get("args", "?")
        raise RuntimeError(f"subprocess blocked by conftest: {cmd!r}. Mock it instead.")

    with (
        patch.object(subprocess, "run", side_effect=_blocked),
        patch.object(subprocess, "Popen", side_effect=_blocked),
        patch.object(subprocess, "call", side_effect=_blocked),
        patch.object(subprocess, "check_call", side_effect=_blocked),
        patch.object(subprocess, "check_output", side_effect=_blocked),
    ):
        yield


@pytest.fixture(autouse=True)
def _block_http(monkeypatch: pytest.MonkeyPatch) -> None:
    """Block real HTTP requests — mock them instead."""

    def _blocked(*args, **kwargs):
        raise RuntimeError("HTTP blocked by conftest. Mock it instead.")

    import httpx

    monkeypatch.setattr(httpx, "Client", _blocked)
    monkeypatch.setattr(httpx, "AsyncClient", _blocked)
    monkeypatch.setattr(httpx, "get", _blocked)
    monkeypatch.setattr(httpx, "post", _blocked)
    monkeypatch.setattr(urllib.request, "urlopen", _blocked)

    try:
        import aiohttp

        monkeypatch.setattr(aiohttp, "ClientSession", _blocked)
    except ImportError:
        pass


@pytest.fixture(autouse=True)
def _block_real_filesystem(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Block filesystem mutations outside tmp_path and .venv."""

    def _is_allowed(path) -> bool:
        resolved = Path(path).resolve()
        return str(resolved).startswith(str(tmp_path)) or str(resolved).startswith(
            str(_PROJECT_ROOT / ".venv")
        )

    def _guard(original):
        def guarded(self, *args, **kwargs):
            if not _is_allowed(self):
                raise PermissionError(f"Test tried to write outside tmp_path: {self}")
            return original(self, *args, **kwargs)

        return guarded

    for method in ("write_text", "write_bytes", "rename", "unlink", "rmdir", "mkdir"):
        monkeypatch.setattr(Path, method, _guard(getattr(Path, method)))

    _orig_open = builtins.open

    def _guarded_open(file, mode="r", *args, **kwargs):
        if any(c in mode for c in ("w", "a", "x", "+")) and not _is_allowed(file):
            raise PermissionError(
                f"Test tried to open for write outside tmp_path: {file}"
            )
        return _orig_open(file, mode, *args, **kwargs)

    monkeypatch.setattr(builtins, "open", _guarded_open)

    def _guarded_shutil(original):
        def guarded(src, dst, *args, **kwargs):
            if not _is_allowed(dst):
                raise PermissionError(f"Test tried to write outside tmp_path: {dst}")
            return original(src, dst, *args, **kwargs)

        return guarded

    monkeypatch.setattr(shutil, "copy2", _guarded_shutil(shutil.copy2))
    monkeypatch.setattr(shutil, "move", _guarded_shutil(shutil.move))


@pytest.fixture(autouse=True)
def _mock_sdk_and_agentpulse(monkeypatch: pytest.MonkeyPatch) -> None:
    """Default-mock the Claude SDK and disable AgentPulse forwarding.

    Tests that exercise SDK behaviour can re-patch agent_service.agent.ClaudeSDKClient
    to inject scripted message streams. Tests that want to verify AgentPulse
    forwarding can re-patch load_agentpulse_endpoint and the post/seed functions.
    """
    import agent_service.agent as agent_mod

    async def _empty_stream():
        if False:
            yield  # never reached — async generator stub

    sdk_instance = MagicMock()
    sdk_instance.connect = AsyncMock()
    sdk_instance.disconnect = AsyncMock()
    sdk_instance.query = AsyncMock()
    sdk_instance.receive_messages = MagicMock(side_effect=_empty_stream)

    sdk_class = MagicMock(return_value=sdk_instance)
    monkeypatch.setattr(agent_mod, "ClaudeSDKClient", sdk_class)
    monkeypatch.setattr(agent_mod, "load_agentpulse_endpoint", lambda *a, **k: None)
    monkeypatch.setattr(agent_mod, "post_statusline", MagicMock(return_value=True))
