# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for Prometheus metrics."""

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from agent_service.app import create_app
from agent_service.config import AgentServiceConfig
from agent_service.metrics import Metrics, create_metrics


@pytest.fixture
def metrics() -> Metrics:
    """Fresh metrics instance with isolated registry."""
    return create_metrics()


class TestMetrics:
    """Tests for metric definitions."""

    def test_create_metrics_returns_all_metrics(self, metrics: Metrics) -> None:
        """create_metrics returns a Metrics object with all counters and gauges."""
        assert metrics.tokens_total is not None
        assert metrics.messages_total is not None
        assert metrics.tool_calls_total is not None
        assert metrics.agent_active_seconds is not None
        assert metrics.ws_connections is not None
        assert metrics.ws_connection_duration is not None
        assert metrics.auth_attempts_total is not None
        assert metrics.errors_total is not None

    def test_counter_increment(self, metrics: Metrics) -> None:
        """Counters can be incremented with labels."""
        metrics.messages_total.labels(direction="inbound").inc()
        metrics.tokens_total.labels(token_type="input", model="opus").inc()
        metrics.auth_attempts_total.labels(result="success").inc()
        metrics.errors_total.labels(error_type="timeout").inc()
        value = metrics.registry.get_sample_value(
            "agent_messages_total", {"direction": "inbound"}
        )
        assert value is not None
        assert value > 0

    def test_gauge_operations(self, metrics: Metrics) -> None:
        """Gauges can be incremented and decremented."""
        metrics.ws_connections.inc()
        metrics.ws_connections.inc()
        metrics.ws_connections.dec()
        value = metrics.registry.get_sample_value("ws_connections_active")
        assert value == 1.0

    def test_registry_isolation(self) -> None:
        """Each create_metrics call gets isolated metrics."""
        m1 = create_metrics()
        m2 = create_metrics()
        m1.messages_total.labels(direction="inbound").inc()
        # m2 should not be affected — separate registry
        assert m1.registry is not m2.registry


class TestMetricsEndpoint:
    def test_metrics_returns_prometheus_format(self, tmp_path: Path) -> None:
        config = AgentServiceConfig(
            agent_working_dir=tmp_path / "agent",
            tls_cert=tmp_path / "cert.pem",
            tls_key=tmp_path / "key.pem",
            tls_ca=tmp_path / "ca.pem",
            oidc_issuer="https://github.com",
            oidc_audience="test",
            authorized_subjects=["test-user"],
            replay_buffer_size=100,
            session_resume_on_startup=False,
            listen_address="0.0.0.0:8443",
        )
        app = create_app(config=config)
        with TestClient(app) as client:
            response = client.get("/metrics")
            assert response.status_code == 200
            assert "text/plain" in response.headers["content-type"]
