# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for the /health endpoint."""

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from agent_service.app import create_app
from agent_service.config import AgentServiceConfig


@pytest.fixture
def test_config(tmp_path: Path) -> AgentServiceConfig:
    """Minimal valid config for testing."""
    return AgentServiceConfig(
        agent_working_dir=tmp_path / "agent",
        tls_cert=tmp_path / "cert.pem",
        tls_key=tmp_path / "key.pem",
        tls_ca=tmp_path / "ca.pem",
        oidc_issuer="https://github.com",
        oidc_audience="test",
        authorized_subjects=["test-user"],
        replay_buffer_size=100,
        session_resume_on_startup=False,
        listen_address="0.0.0.0:8443",
    )


@pytest.fixture
def client(test_config: AgentServiceConfig) -> TestClient:
    """FastAPI test client."""
    app = create_app(config=test_config)
    return TestClient(app)


class TestHealth:
    """Tests for GET /health."""

    def test_health_returns_ok(self, client: TestClient) -> None:
        """Health endpoint returns 200 with status ok."""
        response = client.get("/health")
        assert response.status_code == 200
        assert response.json()["status"] == "ok"

    def test_health_no_auth_required(self, client: TestClient) -> None:
        """Health endpoint is accessible without authentication."""
        response = client.get("/health")
        assert response.status_code == 200
