# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for agent_service.__main__."""

import logging
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

from agent_service.__main__ import EXIT_ERROR, EXIT_SUCCESS, main


@pytest.fixture
def mock_runtime(mocker):
    """Mock load_config, create_app, and uvicorn.run for all CLI tests."""
    cfg = MagicMock()
    cfg.listen_address = "127.0.0.1:8443"
    cfg.tls_cert = Path("/tmp/cert.pem")
    cfg.tls_key = Path("/tmp/key.pem")
    cfg.tls_ca = Path("/tmp/ca.pem")

    return {
        "load_config": mocker.patch(
            "agent_service.__main__.load_config", return_value=cfg
        ),
        "create_app": mocker.patch(
            "agent_service.__main__.create_app", return_value=MagicMock()
        ),
        "uvicorn_run": mocker.patch("agent_service.__main__.uvicorn.run"),
    }


class TestMainBasic:
    """Basic execution and positional argument handling."""

    def test_basic_execution_passes_config_path(self, mock_runtime) -> None:
        with patch("sys.argv", ["agent_service", "myconfig.yaml"]):
            result = main()
        assert result == EXIT_SUCCESS
        call_args = mock_runtime["load_config"].call_args
        assert call_args.kwargs["config_path"] == Path("myconfig.yaml")

    def test_default_config_path(self, mock_runtime) -> None:
        with patch("sys.argv", ["agent_service"]):
            result = main()
        assert result == EXIT_SUCCESS
        call_args = mock_runtime["load_config"].call_args
        assert call_args.kwargs["config_path"] == Path("config.yaml")

    def test_starts_uvicorn_with_config(self, mock_runtime) -> None:
        with patch("sys.argv", ["agent_service", "config.yaml"]):
            main()
        mock_runtime["uvicorn_run"].assert_called_once()
        call_args = mock_runtime["uvicorn_run"].call_args
        assert call_args.kwargs["host"] == "127.0.0.1"
        assert call_args.kwargs["port"] == 8443


class TestDebugFlag:
    """--debug flag sets DEBUG-level logging."""

    def test_debug_sets_debug_level(self, mock_runtime, mocker) -> None:
        cfg_logging = mocker.patch("agent_service.__main__._configure_logging")
        with patch("sys.argv", ["agent_service", "--debug"]):
            main()
        assert cfg_logging.call_args.kwargs["level"] == logging.DEBUG

    def test_debug_off_sets_info_level(self, mock_runtime, mocker) -> None:
        cfg_logging = mocker.patch("agent_service.__main__._configure_logging")
        with patch("sys.argv", ["agent_service"]):
            main()
        assert cfg_logging.call_args.kwargs["level"] == logging.INFO


class TestQuietFlag:
    """--quiet flag raises log level to WARNING."""

    def test_quiet_long_sets_warning_level(self, mock_runtime, mocker) -> None:
        cfg_logging = mocker.patch("agent_service.__main__._configure_logging")
        with patch("sys.argv", ["agent_service", "--quiet"]):
            main()
        assert cfg_logging.call_args.kwargs["level"] == logging.WARNING

    def test_quiet_short_sets_warning_level(self, mock_runtime, mocker) -> None:
        cfg_logging = mocker.patch("agent_service.__main__._configure_logging")
        with patch("sys.argv", ["agent_service", "-q"]):
            main()
        assert cfg_logging.call_args.kwargs["level"] == logging.WARNING


class TestLogFileFlag:
    """--log-file is resolved via expanduser().resolve()."""

    def test_log_file_is_resolved(self, mock_runtime, mocker) -> None:
        cfg_logging = mocker.patch("agent_service.__main__._configure_logging")
        with patch("sys.argv", ["agent_service", "--log-file", "./some.log"]):
            main()
        log_file = cfg_logging.call_args.kwargs["log_file"]
        assert log_file is not None
        assert Path(log_file).is_absolute()

    def test_log_file_none_when_flag_absent(self, mock_runtime, mocker) -> None:
        cfg_logging = mocker.patch("agent_service.__main__._configure_logging")
        with patch("sys.argv", ["agent_service"]):
            main()
        assert cfg_logging.call_args.kwargs["log_file"] is None


class TestCombinedFlags:
    """--debug --quiet together: debug overrides quiet."""

    def test_debug_overrides_quiet(self, mock_runtime, mocker) -> None:
        cfg_logging = mocker.patch("agent_service.__main__._configure_logging")
        with patch("sys.argv", ["agent_service", "--debug", "--quiet"]):
            main()
        assert cfg_logging.call_args.kwargs["level"] == logging.DEBUG

    def test_debug_with_log_file(self, mock_runtime, mocker) -> None:
        cfg_logging = mocker.patch("agent_service.__main__._configure_logging")
        with patch("sys.argv", ["agent_service", "--debug", "--log-file", "a.log"]):
            main()
        assert cfg_logging.call_args.kwargs["level"] == logging.DEBUG
        assert cfg_logging.call_args.kwargs["log_file"] is not None


class TestExitCodes:
    """Exit code contract: EXIT_SUCCESS on clean run, EXIT_ERROR on failure."""

    def test_exit_error_on_config_failure(self, mocker) -> None:
        mocker.patch(
            "agent_service.__main__.load_config",
            side_effect=FileNotFoundError("config.yaml"),
        )
        mocker.patch("agent_service.__main__.uvicorn.run")
        mocker.patch("agent_service.__main__.create_app")
        with patch("sys.argv", ["agent_service"]):
            result = main()
        assert result == EXIT_ERROR

    def test_exit_success_constant(self) -> None:
        assert EXIT_SUCCESS == 0

    def test_exit_error_constant(self) -> None:
        assert EXIT_ERROR == 1
