# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for agent_service.ws_manager."""

from unittest.mock import AsyncMock, MagicMock

import pytest

from agent_service.model import ServerMessage
from agent_service.ws_manager import WebSocketManager


def _make_mock_ws() -> AsyncMock:
    """Create a mock WebSocket with send_json."""
    ws = AsyncMock()
    ws.send_json = AsyncMock()
    return ws


def _make_message(*, sequence: int = 0, timestamp: str = "") -> ServerMessage:
    return ServerMessage(
        type="event",
        agent_id="pa-main",
        session_id="abc123",
        sequence=sequence,
        timestamp=timestamp,
    )


@pytest.fixture
def metrics() -> MagicMock:
    m = MagicMock()
    m.ws_connections = MagicMock()
    m.ws_connections.inc = MagicMock()
    m.ws_connections.dec = MagicMock()
    return m


@pytest.fixture
def manager(metrics: MagicMock) -> WebSocketManager:
    return WebSocketManager(replay_buffer_size=10, metrics=metrics)


class TestWebSocketManager:
    """Tests for WebSocketManager."""

    async def test_connect_adds_to_set(self, manager: WebSocketManager) -> None:
        ws = _make_mock_ws()
        await manager.connect(ws=ws)
        assert manager.connection_count == 1

    async def test_disconnect_removes_from_set(self, manager: WebSocketManager) -> None:
        ws = _make_mock_ws()
        await manager.connect(ws=ws)
        await manager.disconnect(ws=ws)
        assert manager.connection_count == 0

    async def test_broadcast_sends_to_all(self, manager: WebSocketManager) -> None:
        ws1 = _make_mock_ws()
        ws2 = _make_mock_ws()
        await manager.connect(ws=ws1)
        await manager.connect(ws=ws2)
        msg = _make_message()
        await manager.broadcast(message=msg)
        assert ws1.send_json.call_count == 1
        assert ws2.send_json.call_count == 1

    async def test_broadcast_assigns_sequence(self, manager: WebSocketManager) -> None:
        ws = _make_mock_ws()
        await manager.connect(ws=ws)
        await manager.broadcast(message=_make_message())
        await manager.broadcast(message=_make_message())
        sent1 = ws.send_json.call_args_list[0][1]["data"]
        sent2 = ws.send_json.call_args_list[1][1]["data"]
        assert sent1["sequence"] == 1
        assert sent2["sequence"] == 2

    async def test_broadcast_assigns_timestamp(self, manager: WebSocketManager) -> None:
        ws = _make_mock_ws()
        await manager.connect(ws=ws)
        await manager.broadcast(message=_make_message())
        sent = ws.send_json.call_args_list[0][1]["data"]
        assert sent["timestamp"] != ""

    async def test_replay_by_sequence(self, manager: WebSocketManager) -> None:
        ws = _make_mock_ws()
        await manager.connect(ws=ws)
        for _ in range(5):
            await manager.broadcast(message=_make_message())
        ws.send_json.reset_mock()
        replay_ws = _make_mock_ws()
        await manager.replay(ws=replay_ws, since=3)
        assert replay_ws.send_json.call_count == 2
        replayed = [call[1]["data"] for call in replay_ws.send_json.call_args_list]
        assert [e["sequence"] for e in replayed] == [4, 5]

    async def test_replay_buffer_bounded(self, manager: WebSocketManager) -> None:
        """Buffer does not grow beyond replay_buffer_size."""
        ws = _make_mock_ws()
        await manager.connect(ws=ws)
        for _ in range(20):
            await manager.broadcast(message=_make_message())
        ws.send_json.reset_mock()
        replay_ws = _make_mock_ws()
        await manager.replay(ws=replay_ws, since=0)
        assert replay_ws.send_json.call_count == 10

    async def test_broadcast_handles_broken_connection(
        self, manager: WebSocketManager, metrics: MagicMock
    ) -> None:
        """Broken WebSocket is silently removed during broadcast."""
        good_ws = _make_mock_ws()
        bad_ws = _make_mock_ws()
        bad_ws.send_json.side_effect = Exception("broken pipe")
        await manager.connect(ws=good_ws)
        await manager.connect(ws=bad_ws)
        await manager.broadcast(message=_make_message())
        assert good_ws.send_json.call_count == 1
        assert manager.connection_count == 1

    async def test_disconnect_idempotent(self, manager: WebSocketManager) -> None:
        """Disconnecting a non-connected ws does not error."""
        ws = _make_mock_ws()
        await manager.disconnect(ws=ws)
        assert manager.connection_count == 0
