# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for agent_service.model."""

import pytest

from agent_service.model import (
    ClientMessage,
    ErrorMessage,
    EventMessage,
    ReplayRequest,
    ServerMessage,
)


class TestServerMessage:
    """Tests for server-to-client message types."""

    def test_required_fields(self) -> None:
        """All required fields must be present."""
        msg = ServerMessage(
            type="event",
            agent_id="pa-main",
            session_id="abc123",
            sequence=1,
            timestamp="2026-04-05T18:30:00Z",
        )
        assert msg.type == "event"
        assert msg.sequence == 1

    def test_missing_required_field_raises(self) -> None:
        """Missing required field raises ValidationError."""
        with pytest.raises(Exception):
            ServerMessage(type="event")

    def test_extra_fields_allowed(self) -> None:
        """Open schema — extra fields are tolerated."""
        msg = ServerMessage(
            type="event",
            agent_id="pa-main",
            session_id="abc123",
            sequence=1,
            timestamp="2026-04-05T18:30:00Z",
            custom_field="extra",
        )
        data = msg.model_dump()
        assert data["custom_field"] == "extra"

    def test_serialization_round_trip(self) -> None:
        """model_dump -> ServerMessage produces identical object."""
        msg = ServerMessage(
            type="event",
            agent_id="pa-main",
            session_id="abc123",
            sequence=1,
            timestamp="2026-04-05T18:30:00Z",
        )
        data = msg.model_dump()
        restored = ServerMessage(**data)
        assert restored == msg


class TestEventMessage:
    """Tests for EventMessage subtype."""

    def test_event_message_fields(self) -> None:
        """EventMessage has event_type and data fields."""
        msg = EventMessage(
            type="event",
            agent_id="pa-main",
            session_id="abc123",
            sequence=1,
            timestamp="2026-04-05T18:30:00Z",
            event_type="PreToolUse",
            data={"tool_name": "Read"},
        )
        assert msg.event_type == "PreToolUse"
        assert msg.data["tool_name"] == "Read"


class TestErrorMessage:
    """Tests for ErrorMessage subtype."""

    def test_error_message_fields(self) -> None:
        """ErrorMessage has content field."""
        msg = ErrorMessage(
            type="error",
            agent_id="pa-main",
            session_id="abc123",
            sequence=1,
            timestamp="2026-04-05T18:30:00Z",
            content="something went wrong",
        )
        assert msg.content == "something went wrong"


class TestClientMessage:
    """Tests for client-to-server message types."""

    def test_message_with_source(self) -> None:
        """Client message with optional source field."""
        msg = ClientMessage(
            type="message",
            content="hello",
            source="discord",
        )
        assert msg.source == "discord"

    def test_message_without_source(self) -> None:
        """Client message without source defaults to None."""
        msg = ClientMessage(
            type="message",
            content="hello",
        )
        assert msg.source is None


class TestReplayRequest:
    """Tests for replay request message."""

    def test_replay_with_sequence(self) -> None:
        """Replay request with sequence number."""
        msg = ReplayRequest(
            type="replay",
            since=12345,
        )
        assert msg.since == 12345

    def test_replay_with_timestamp(self) -> None:
        """Replay request with ISO timestamp."""
        msg = ReplayRequest(
            type="replay",
            since="2026-04-05T12:00:00Z",
        )
        assert msg.since == "2026-04-05T12:00:00Z"
