# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for agent_service.auth."""

import asyncio
import time
from unittest.mock import patch

import jwt as pyjwt
import pytest
from cryptography.hazmat.primitives.asymmetric import rsa

from agent_service.auth import AuthContext, OIDCValidator, _extract_bearer_token
from fastapi import HTTPException


def _generate_rsa_keypair():
    """Generate RSA key pair for test JWT signing."""
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    public_key = private_key.public_key()
    return private_key, public_key


def _sign_token(*, private_key, claims: dict, headers: dict | None = None) -> str:
    """Sign a JWT with the given private key."""
    return pyjwt.encode(
        payload=claims,
        key=private_key,
        algorithm="RS256",
        headers=headers,
    )


def _run(coro):
    # asyncio.run() conflicts with pytest-asyncio `auto` mode if an outer loop
    # is ever introduced; use a dedicated loop per sync test instead.
    loop = asyncio.new_event_loop()
    try:
        return loop.run_until_complete(coro)
    finally:
        loop.close()


class TestExtractBearerToken:
    """Tests for bearer token extraction."""

    def test_valid_bearer(self) -> None:
        token = _extract_bearer_token(authorization="Bearer abc123")
        assert token == "abc123"

    def test_missing_header_raises(self) -> None:
        with pytest.raises(HTTPException) as exc_info:
            _extract_bearer_token(authorization=None)
        assert exc_info.value.status_code == 401

    def test_invalid_format_raises(self) -> None:
        with pytest.raises(HTTPException) as exc_info:
            _extract_bearer_token(authorization="Basic abc123")
        assert exc_info.value.status_code == 401


class TestOIDCValidator:
    """Tests for OIDCValidator."""

    @pytest.fixture
    def keypair(self):
        return _generate_rsa_keypair()

    @pytest.fixture
    def validator(self) -> OIDCValidator:
        return OIDCValidator(
            issuer="https://github.com",
            audience="test-app",
            authorized_subjects=["user-1", "user-2"],
        )

    def test_valid_token_accepted(self, validator: OIDCValidator, keypair) -> None:
        """Valid token with authorized subject passes."""
        private_key, public_key = keypair
        claims = {
            "iss": "https://github.com",
            "aud": "test-app",
            "sub": "user-1",
            "exp": int(time.time()) + 3600,
        }
        token = _sign_token(
            private_key=private_key, claims=claims, headers={"kid": "test-key"}
        )
        with patch.object(
            validator,
            "_get_signing_key",
            return_value=public_key,
        ):
            result = _run(validator.validate_token(token=token))
        assert result.subject == "user-1"

    def test_expired_token_rejected(self, validator: OIDCValidator, keypair) -> None:
        """Expired token is rejected."""
        private_key, public_key = keypair
        claims = {
            "iss": "https://github.com",
            "aud": "test-app",
            "sub": "user-1",
            "exp": int(time.time()) - 3600,
        }
        token = _sign_token(
            private_key=private_key, claims=claims, headers={"kid": "test-key"}
        )
        with patch.object(
            validator,
            "_get_signing_key",
            return_value=public_key,
        ):
            with pytest.raises(pyjwt.ExpiredSignatureError):
                _run(validator.validate_token(token=token))

    def test_wrong_audience_rejected(self, validator: OIDCValidator, keypair) -> None:
        """Token with wrong audience is rejected."""
        private_key, public_key = keypair
        claims = {
            "iss": "https://github.com",
            "aud": "wrong-app",
            "sub": "user-1",
            "exp": int(time.time()) + 3600,
        }
        token = _sign_token(
            private_key=private_key, claims=claims, headers={"kid": "test-key"}
        )
        with patch.object(
            validator,
            "_get_signing_key",
            return_value=public_key,
        ):
            with pytest.raises(pyjwt.InvalidAudienceError):
                _run(validator.validate_token(token=token))

    def test_unauthorized_subject_rejected(
        self, validator: OIDCValidator, keypair
    ) -> None:
        """Token with unauthorized subject is rejected."""
        private_key, public_key = keypair
        claims = {
            "iss": "https://github.com",
            "aud": "test-app",
            "sub": "unknown-user",
            "exp": int(time.time()) + 3600,
        }
        token = _sign_token(
            private_key=private_key, claims=claims, headers={"kid": "test-key"}
        )
        with patch.object(
            validator,
            "_get_signing_key",
            return_value=public_key,
        ):
            with pytest.raises(PermissionError):
                _run(validator.validate_token(token=token))

    def test_wrong_issuer_rejected(self, validator, keypair):
        """Token with wrong issuer is rejected."""
        private_key, public_key = keypair
        claims = {
            "iss": "https://evil.com",
            "aud": "test-app",
            "sub": "user-1",
            "exp": int(time.time()) + 3600,
        }
        token = _sign_token(
            private_key=private_key, claims=claims, headers={"kid": "test-key"}
        )
        with (
            patch.object(validator, "_get_signing_key", return_value=public_key),
            pytest.raises(pyjwt.InvalidIssuerError),
        ):
            _run(validator.validate_token(token=token))


class TestAuthContext:
    """Tests for AuthContext."""

    def test_auth_context_fields(self) -> None:
        ctx = AuthContext(subject="user-1", claims={"sub": "user-1"})
        assert ctx.subject == "user-1"
        assert ctx.claims["sub"] == "user-1"

    def test_auth_context_default_claims(self) -> None:
        ctx = AuthContext(subject="user-1")
        assert ctx.claims == {}
