# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for agent_service.agent."""

import asyncio
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from agent_service.agent import AgentClient


@pytest.fixture
def on_event() -> AsyncMock:
    return AsyncMock()


@pytest.fixture
def metrics() -> MagicMock:
    m = MagicMock()
    m.tokens_total = MagicMock()
    m.messages_total = MagicMock()
    m.tool_calls_total = MagicMock()
    m.agent_active_seconds = MagicMock()
    m.errors_total = MagicMock()
    return m


@pytest.fixture
def agent(tmp_path: Path, on_event: AsyncMock, metrics: MagicMock) -> AgentClient:
    return AgentClient(
        working_dir=tmp_path / "agent",
        resume_on_startup=False,
        on_event=on_event,
        metrics=metrics,
        agent_id="test-agent",
    )


class TestAgentClient:
    """Tests for AgentClient."""

    def test_status_before_start(self, agent: AgentClient) -> None:
        """Status reflects unstarted agent."""
        status = agent.status
        assert status["agent_id"] == "test-agent"
        assert status["session_id"] is None

    def test_status_has_working_dir(self, agent: AgentClient) -> None:
        """Status includes working directory."""
        status = agent.status
        assert "agent" in status["working_dir"]

    def test_status_has_timestamp(self, agent: AgentClient) -> None:
        """Status includes current timestamp."""
        status = agent.status
        assert status["timestamp"] is not None

    async def test_send_message_increments_counter(
        self, agent: AgentClient, metrics: MagicMock
    ) -> None:
        """Sending a message increments the inbound counter."""
        await agent.send_message(content="hello")
        metrics.messages_total.labels.assert_called_with(direction="inbound")
        metrics.messages_total.labels().inc.assert_called_once()

    async def test_clear_resets_session(self, agent: AgentClient) -> None:
        """Clear resets the session ID."""
        agent._session_id = "old-session"
        await agent.clear()
        assert agent.status["session_id"] is None

    async def test_sequential_message_processing(self, agent: AgentClient) -> None:
        """Messages are processed sequentially via lock."""
        call_order: list[int] = []

        async def slow_process(*, content, source=None):
            call_order.append(1)
            await asyncio.sleep(0.05)
            call_order.append(2)

        with patch.object(agent, "_process_message", side_effect=slow_process):
            await asyncio.gather(
                agent.send_message(content="a"),
                agent.send_message(content="b"),
            )
        # Sequential: should be 1,2,1,2 not 1,1,2,2
        assert call_order == [1, 2, 1, 2]
