# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for the WebSocket endpoint."""

from pathlib import Path
from unittest.mock import AsyncMock

import pytest
from fastapi.testclient import TestClient

from agent_service.agent import AgentClient
from agent_service.app import create_app
from agent_service.auth import AuthContext, require_auth_ws
from agent_service.config import AgentServiceConfig
from agent_service.metrics import create_metrics
from agent_service.ws_manager import WebSocketManager


@pytest.fixture
def test_config(tmp_path: Path) -> AgentServiceConfig:
    return AgentServiceConfig(
        agent_working_dir=tmp_path / "agent",
        tls_cert=tmp_path / "cert.pem",
        tls_key=tmp_path / "key.pem",
        tls_ca=tmp_path / "ca.pem",
        oidc_issuer="https://github.com",
        oidc_audience="test",
        authorized_subjects=["test-user"],
        replay_buffer_size=100,
        session_resume_on_startup=False,
        listen_address="0.0.0.0:8443",
    )


def _mock_auth_ws() -> AuthContext:
    return AuthContext(subject="test-user", claims={"sub": "test-user"})


@pytest.fixture
def client(test_config: AgentServiceConfig, tmp_path: Path) -> TestClient:
    app = create_app(config=test_config)
    app.dependency_overrides[require_auth_ws] = _mock_auth_ws

    metrics = create_metrics()
    app.state.metrics = metrics
    app.state.ws_manager = WebSocketManager(replay_buffer_size=100, metrics=metrics)
    app.state.agent = AgentClient(
        working_dir=tmp_path / "agent",
        resume_on_startup=False,
        on_event=AsyncMock(),
        metrics=metrics,
        agent_id="test-agent",
    )
    return TestClient(app)


class TestWebSocket:
    """Tests for wss://.../agent/ws."""

    def test_connect_and_send_message(self, client: TestClient) -> None:
        """Client can connect and send a message."""
        with client.websocket_connect("/agent/ws") as ws:
            ws.send_json({"type": "message", "content": "hello"})
        # Connection was accepted and message processed without error
        # Agent's send_message was invoked (SDK is stubbed, no response)
        assert (
            client.app.state.ws_manager.connection_count == 0
        )  # disconnected after with-block

    def test_replay_as_first_message(self, client: TestClient) -> None:
        """Replay request accepted as first message."""
        with client.websocket_connect("/agent/ws") as ws:
            ws.send_json({"type": "replay", "since": 0})

    def test_replay_rejected_after_first_message(self, client: TestClient) -> None:
        """Replay request after first message returns error."""
        with client.websocket_connect("/agent/ws") as ws:
            ws.send_json({"type": "message", "content": "hello"})
            ws.send_json({"type": "replay", "since": 0})
            response = ws.receive_json()
            assert "error" in response

    def test_message_with_source(self, client: TestClient) -> None:
        """Message with source field is accepted."""
        with client.websocket_connect("/agent/ws") as ws:
            ws.send_json(
                {
                    "type": "message",
                    "content": "hello",
                    "source": "discord",
                }
            )
