# Generated By: Claude Code (Claude Opus 4.7 (1M context))

"""Tests for agent_service.agent."""

import asyncio
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

import agent_service.agent as agent_mod
from agent_service.agent import AgentClient
from agent_service.model import ErrorMessage, EventMessage


@pytest.fixture
def on_event() -> AsyncMock:
    return AsyncMock()


@pytest.fixture
def metrics() -> MagicMock:
    m = MagicMock()
    m.tokens_total = MagicMock()
    m.messages_total = MagicMock()
    m.tool_calls_total = MagicMock()
    m.agent_active_seconds = MagicMock()
    m.errors_total = MagicMock()
    return m


@pytest.fixture
def agent(tmp_path: Path, on_event: AsyncMock, metrics: MagicMock) -> AgentClient:
    return AgentClient(
        working_dir=tmp_path / "agent",
        resume_on_startup=False,
        on_event=on_event,
        metrics=metrics,
        agent_id="test-agent",
    )


def _make_assistant_message(*, blocks: list, usage: dict | None = None):
    """Build a duck-typed AssistantMessage stand-in. The agent code uses
    isinstance() so tests must use the real class — but with controlled fields.
    """
    from claude_agent_sdk import AssistantMessage

    return AssistantMessage.__new__(AssistantMessage).__class__(
        content=blocks,
        usage=usage,
        model="test-model",
        parent_tool_use_id=None,
    )


def _make_stream_event(event_dict: dict):
    from claude_agent_sdk import StreamEvent

    return StreamEvent.__new__(StreamEvent).__class__(
        uuid="stream-event-uuid",
        session_id="test-session",
        parent_tool_use_id=None,
        event=event_dict,
    )


def _make_result_message(
    *,
    session_id: str = "result-session",
    is_error: bool = False,
    usage: dict | None = None,
    model_usage: dict | None = None,
    total_cost_usd: float | None = 0.001,
):
    """ResultMessage is a dataclass; construct it directly with required fields."""
    from claude_agent_sdk import ResultMessage

    return ResultMessage(
        subtype="success",
        duration_ms=100,
        duration_api_ms=80,
        is_error=is_error,
        num_turns=1,
        session_id=session_id,
        total_cost_usd=total_cost_usd,
        usage=usage,
        result="ok",
        model_usage=model_usage,
    )


class TestAgentClient:
    """Tests for AgentClient."""

    def test_status_before_start(self, agent: AgentClient) -> None:
        status = agent.status
        assert status["agent_id"] == "test-agent"
        assert status["session_id"] is None
        assert status["total_cost_usd"] == 0.0

    def test_status_has_working_dir(self, agent: AgentClient) -> None:
        assert "agent" in agent.status["working_dir"]

    def test_status_has_timestamp(self, agent: AgentClient) -> None:
        assert agent.status["timestamp"] is not None

    async def test_send_message_increments_counter(
        self, agent: AgentClient, metrics: MagicMock
    ) -> None:
        """Sending a message increments the inbound counter even when the SDK
        client is None (emits an error and returns)."""
        await agent.send_message(content="hello")
        metrics.messages_total.labels.assert_called_with(direction="inbound")
        metrics.messages_total.labels().inc.assert_called_once()

    async def test_send_before_start_emits_error(
        self, agent: AgentClient, on_event: AsyncMock
    ) -> None:
        await agent.send_message(content="hi")
        on_event.assert_awaited()
        msg = on_event.await_args.args[0]
        assert isinstance(msg, ErrorMessage)
        assert "not connected" in msg.content

    async def test_clear_resets_session_and_reconnects(
        self, agent: AgentClient
    ) -> None:
        await agent.start()
        agent._session_id = "old-session"
        await agent.clear()
        assert agent.status["session_id"] is None

    async def test_clear_preserves_accumulator(self, agent: AgentClient) -> None:
        """Cost/token totals must NOT reset on /clear (process-scoped)."""
        await agent.start()
        agent._accumulator.total_cost_usd = 1.50
        agent._accumulator.total_input_tokens = 1000
        await agent.clear()
        assert agent._accumulator.total_cost_usd == 1.50
        assert agent._accumulator.total_input_tokens == 1000
        # Per-turn snapshot IS reset
        assert agent._accumulator.last_input_tokens == 0

    async def test_sequential_message_processing(self, agent: AgentClient) -> None:
        """Messages are processed sequentially via lock."""
        call_order: list[int] = []

        async def slow_process(*, content, source=None):
            call_order.append(1)
            await asyncio.sleep(0.05)
            call_order.append(2)

        with patch.object(agent, "_process_message", side_effect=slow_process):
            await asyncio.gather(
                agent.send_message(content="a"),
                agent.send_message(content="b"),
            )
        assert call_order == [1, 2, 1, 2]


class TestStreamingDispatch:
    """Tests for _handle_message routing logic."""

    async def test_stream_event_text_delta_emits_event(
        self, agent: AgentClient, on_event: AsyncMock
    ) -> None:
        msg = _make_stream_event(
            {
                "type": "content_block_delta",
                "delta": {"type": "text_delta", "text": "hello"},
            }
        )
        await agent._handle_message(msg)
        on_event.assert_awaited_once()
        emitted = on_event.await_args.args[0]
        assert isinstance(emitted, EventMessage)
        assert emitted.event_type == "text_delta"
        assert emitted.data == {"text": "hello"}

    async def test_stream_event_non_text_delta_ignored(
        self, agent: AgentClient, on_event: AsyncMock
    ) -> None:
        msg = _make_stream_event({"type": "message_start", "message": {"id": "x"}})
        await agent._handle_message(msg)
        on_event.assert_not_awaited()

    async def test_assistant_message_tool_use_emits_event(
        self, agent: AgentClient, on_event: AsyncMock, metrics: MagicMock
    ) -> None:
        from claude_agent_sdk import ToolUseBlock

        block = ToolUseBlock(id="t1", name="Bash", input={"cmd": "ls"})
        msg = _make_assistant_message(blocks=[block], usage={"input_tokens": 100})
        await agent._handle_message(msg)
        metrics.tool_calls_total.inc.assert_called_once()
        on_event.assert_awaited_once()
        emitted = on_event.await_args.args[0]
        assert emitted.event_type == "tool_use"
        assert emitted.data["name"] == "Bash"

    async def test_assistant_message_text_block_skipped(
        self, agent: AgentClient, on_event: AsyncMock
    ) -> None:
        """TextBlocks must NOT be re-emitted (StreamEvent already handled them)."""
        from claude_agent_sdk import TextBlock

        block = TextBlock(text="hello world")
        msg = _make_assistant_message(blocks=[block])
        await agent._handle_message(msg)
        on_event.assert_not_awaited()

    async def test_assistant_message_captures_usage_for_snapshot(
        self, agent: AgentClient
    ) -> None:
        msg = _make_assistant_message(
            blocks=[],
            usage={
                "input_tokens": 50,
                "cache_read_input_tokens": 1000,
                "cache_creation_input_tokens": 200,
            },
        )
        await agent._handle_message(msg)
        assert agent._last_assistant_usage == {
            "input_tokens": 50,
            "cache_read_input_tokens": 1000,
            "cache_creation_input_tokens": 200,
        }


class TestResultHandling:
    """Tests for _handle_result accumulation, metrics, and emission."""

    async def test_result_updates_accumulator(self, agent: AgentClient) -> None:
        msg = _make_result_message(
            session_id="s1",
            usage={"input_tokens": 100, "output_tokens": 50},
            model_usage={"claude-opus-4-7": {"outputTokens": 50}},
            total_cost_usd=0.05,
        )
        await agent._handle_result(msg)
        assert agent._accumulator.total_cost_usd == pytest.approx(0.05)
        assert agent._accumulator.total_input_tokens == 100
        assert agent._accumulator.total_output_tokens == 50
        assert agent._accumulator.session_id == "s1"

    async def test_result_records_token_metrics_per_type(
        self, agent: AgentClient, metrics: MagicMock
    ) -> None:
        msg = _make_result_message(
            usage={
                "input_tokens": 100,
                "output_tokens": 50,
                "cache_read_input_tokens": 1000,
                "cache_creation_input_tokens": 200,
            },
            model_usage={"claude-opus-4-7": {"outputTokens": 50}},
        )
        await agent._handle_result(msg)
        # Verify each token_type label was used
        label_calls = [c.kwargs for c in metrics.tokens_total.labels.call_args_list]
        token_types = {c.get("token_type") for c in label_calls}
        assert token_types == {"input", "output", "cache_read", "cache_creation"}

    async def test_result_skips_zero_token_metrics(
        self, agent: AgentClient, metrics: MagicMock
    ) -> None:
        msg = _make_result_message(
            usage={"input_tokens": 100, "output_tokens": 0},
            model_usage={"m": {"outputTokens": 0}},
        )
        await agent._handle_result(msg)
        label_calls = [c.kwargs for c in metrics.tokens_total.labels.call_args_list]
        token_types = [c.get("token_type") for c in label_calls]
        assert token_types == ["input"]

    async def test_result_error_emits_error_message(
        self, agent: AgentClient, on_event: AsyncMock, metrics: MagicMock
    ) -> None:
        msg = _make_result_message(is_error=True, total_cost_usd=None)
        await agent._handle_result(msg)
        metrics.errors_total.labels.assert_called_with(error_type="result")
        emitted = on_event.await_args.args[0]
        assert isinstance(emitted, ErrorMessage)

    async def test_result_emits_event_with_session_id(
        self, agent: AgentClient, on_event: AsyncMock
    ) -> None:
        msg = _make_result_message(session_id="abc-123")
        await agent._handle_result(msg)
        emitted = on_event.await_args.args[0]
        assert emitted.event_type == "result"
        assert emitted.data["session_id"] == "abc-123"
        assert agent._session_id == "abc-123"


class TestSDKOptions:
    """Tests for ClaudeAgentOptions wiring."""

    async def test_chat_model_pinned_when_set(
        self, tmp_path: Path, on_event: AsyncMock, metrics: MagicMock
    ) -> None:
        agent = AgentClient(
            working_dir=tmp_path / "agent",
            resume_on_startup=False,
            on_event=on_event,
            metrics=metrics,
            agent_id="test-agent",
            chat_model="claude-opus-4-7[1m]",
        )
        await agent.start()
        # ClaudeAgentOptions was constructed with model=
        sdk_class = agent_mod.ClaudeSDKClient
        call_kwargs = sdk_class.call_args.kwargs
        assert "options" in call_kwargs
        assert call_kwargs["options"].model == "claude-opus-4-7[1m]"

    async def test_chat_model_omitted_when_unset(
        self, tmp_path: Path, on_event: AsyncMock, metrics: MagicMock
    ) -> None:
        agent = AgentClient(
            working_dir=tmp_path / "agent",
            resume_on_startup=False,
            on_event=on_event,
            metrics=metrics,
            agent_id="test-agent",
            chat_model=None,
        )
        await agent.start()
        sdk_class = agent_mod.ClaudeSDKClient
        call_kwargs = sdk_class.call_args.kwargs
        # When chat_model is None, options.model should be the default (None or unset)
        assert call_kwargs["options"].model is None

    async def test_resume_on_startup_uses_last_session(
        self, tmp_path: Path, on_event: AsyncMock, metrics: MagicMock
    ) -> None:
        agent = AgentClient(
            working_dir=tmp_path / "agent",
            resume_on_startup=True,
            on_event=on_event,
            metrics=metrics,
            agent_id="test-agent",
        )
        with patch.object(AgentClient, "_find_last_session", return_value="prior-sess"):
            await agent.start()
        sdk_class = agent_mod.ClaudeSDKClient
        call_kwargs = sdk_class.call_args.kwargs
        assert call_kwargs["options"].resume == "prior-sess"

    async def test_fresh_start_passes_resume_none(
        self, tmp_path: Path, on_event: AsyncMock, metrics: MagicMock
    ) -> None:
        agent = AgentClient(
            working_dir=tmp_path / "agent",
            resume_on_startup=False,
            on_event=on_event,
            metrics=metrics,
            agent_id="test-agent",
        )
        await agent.start()
        sdk_class = agent_mod.ClaudeSDKClient
        call_kwargs = sdk_class.call_args.kwargs
        assert call_kwargs["options"].resume is None
