# Generated By: Claude Code (Claude Opus 4.7 (1M context))

"""Tests for agent_service.agentpulse_statusline (lifted module)."""

from __future__ import annotations

import json
import urllib.error
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from agent_service import agentpulse_statusline as aps
from agent_service.agentpulse_statusline import (
    DEFAULT_CONTEXT_WINDOW,
    SeedResult,
    SessionAccumulator,
    build_payload,
    extract_model_name,
    load_agentpulse_endpoint,
    lookup_context_window,
    merge_agentpulse_seed,
    post_statusline,
)


class TestLookupContextWindow:
    def test_1m_model_gets_1m_window(self) -> None:
        assert lookup_context_window("claude-opus-4-7[1m]") == 1_000_000

    def test_1m_with_dated_suffix(self) -> None:
        assert lookup_context_window("claude-opus-4-7[1m]-20251101") == 1_000_000

    def test_regular_claude_model_gets_default(self) -> None:
        assert lookup_context_window("claude-opus-4-6") == DEFAULT_CONTEXT_WINDOW

    def test_empty_name_returns_default(self) -> None:
        assert lookup_context_window("") == DEFAULT_CONTEXT_WINDOW

    def test_unknown_name_returns_default_with_warning(self) -> None:
        assert lookup_context_window("not-a-claude-model") == DEFAULT_CONTEXT_WINDOW


class TestExtractModelName:
    def test_empty_returns_empty_string(self) -> None:
        assert extract_model_name(None) == ""
        assert extract_model_name({}) == ""

    def test_single_model_returned(self) -> None:
        assert extract_model_name({"claude-opus-4-7": {"outputTokens": 10}}) == (
            "claude-opus-4-7"
        )

    def test_multiple_models_picks_most_output_tokens(self) -> None:
        usage = {
            "claude-haiku": {"outputTokens": 5},
            "claude-opus": {"outputTokens": 100},
        }
        assert extract_model_name(usage) == "claude-opus"

    def test_tiebreak_alphabetical(self) -> None:
        usage = {
            "model-z": {"outputTokens": 0},
            "model-a": {"outputTokens": 0},
        }
        assert extract_model_name(usage) == "model-a"

    def test_handles_non_dict_value(self) -> None:
        usage = {"x": "not-a-dict", "y": {"outputTokens": 5}}
        assert extract_model_name(usage) == "y"


class TestSessionAccumulator:
    def test_initial_state_zero(self) -> None:
        acc = SessionAccumulator()
        assert acc.total_cost_usd == 0.0
        assert acc.total_input_tokens == 0
        assert acc.session_id == ""

    def test_record_result_accumulates_cost_and_tokens(self) -> None:
        acc = SessionAccumulator()
        acc.record_result(
            session_id="s1",
            total_cost_usd=0.10,
            usage={"input_tokens": 100, "output_tokens": 50},
            duration_ms=200,
            duration_api_ms=150,
            model_name="claude-opus",
        )
        acc.record_result(
            session_id="s1",
            total_cost_usd=0.05,
            usage={"input_tokens": 30, "output_tokens": 20},
            duration_ms=80,
            duration_api_ms=60,
        )
        assert acc.total_cost_usd == pytest.approx(0.15)
        assert acc.total_input_tokens == 130
        assert acc.total_output_tokens == 70
        assert acc.total_duration_ms == 280
        assert acc.total_api_duration_ms == 210
        assert acc.last_model_name == "claude-opus"

    def test_record_result_handles_none_cost(self) -> None:
        acc = SessionAccumulator()
        acc.record_result(
            session_id="s1",
            total_cost_usd=None,
            usage=None,
            duration_ms=0,
            duration_api_ms=0,
        )
        assert acc.total_cost_usd == 0.0

    def test_record_turn_snapshot_replaces_per_turn_view(self) -> None:
        acc = SessionAccumulator()
        acc.record_turn_snapshot(
            {
                "input_tokens": 100,
                "cache_read_input_tokens": 5000,
                "cache_creation_input_tokens": 1000,
            }
        )
        assert acc.last_input_tokens == 100
        assert acc.last_cache_read_tokens == 5000
        assert acc.last_cache_creation_tokens == 1000

    def test_record_turn_snapshot_none_keeps_previous(self) -> None:
        acc = SessionAccumulator()
        acc.record_turn_snapshot({"input_tokens": 50})
        acc.record_turn_snapshot(None)
        assert acc.last_input_tokens == 50

    def test_reset_snapshot_zeros_per_turn_only(self) -> None:
        acc = SessionAccumulator()
        acc.total_cost_usd = 1.0
        acc.last_input_tokens = 100
        acc.reset_snapshot()
        assert acc.last_input_tokens == 0
        assert acc.total_cost_usd == 1.0  # preserved


class TestBuildPayload:
    def test_payload_shape(self) -> None:
        acc = SessionAccumulator()
        acc.session_id = "abc"
        acc.total_cost_usd = 1.23
        acc.total_input_tokens = 1000
        acc.total_output_tokens = 500
        acc.total_duration_ms = 5000
        acc.total_api_duration_ms = 4000
        acc.last_input_tokens = 100
        acc.last_cache_read_tokens = 500
        acc.last_cache_creation_tokens = 50
        acc.last_model_name = "claude-opus-4-7"
        payload = build_payload(acc, pid=123, cwd="/work", source_system="host1")
        assert payload["session_id"] == "abc"
        assert payload["pid"] == 123
        assert payload["workspace"]["project_dir"] == "/work"
        assert payload["cost"]["total_cost_usd"] == 1.23
        cw = payload["context_window"]
        assert cw["total_input_tokens"] == 1000
        assert cw["context_window_size"] == DEFAULT_CONTEXT_WINDOW
        assert cw["current_usage"]["cache_read_input_tokens"] == 500
        assert payload["model"]["display_name"] == "claude-opus-4-7"

    def test_payload_used_pct_for_1m_model(self) -> None:
        acc = SessionAccumulator()
        acc.last_input_tokens = 100_000
        acc.last_model_name = "claude-opus-4-7[1m]"
        payload = build_payload(acc, pid=1, cwd="/x", source_system="h")
        assert payload["context_window"]["context_window_size"] == 1_000_000
        assert payload["context_window"]["used_percentage"] == 10.0


class TestPostStatusline:
    def test_post_success_returns_true(self) -> None:
        resp_cm = MagicMock()
        resp = MagicMock()
        resp.status = 200
        resp_cm.__enter__ = MagicMock(return_value=resp)
        resp_cm.__exit__ = MagicMock(return_value=False)
        with patch.object(aps.urllib.request, "urlopen", return_value=resp_cm):
            assert post_statusline("h", 8080, {"session_id": "s"}) is True

    def test_post_non_2xx_returns_false(self) -> None:
        resp_cm = MagicMock()
        resp = MagicMock()
        resp.status = 500
        resp_cm.__enter__ = MagicMock(return_value=resp)
        resp_cm.__exit__ = MagicMock(return_value=False)
        with patch.object(aps.urllib.request, "urlopen", return_value=resp_cm):
            assert post_statusline("h", 8080, {"session_id": "s"}) is False

    def test_post_http_error_returns_false(self) -> None:
        err = urllib.error.HTTPError("http://x", 503, "down", {}, None)
        with patch.object(aps.urllib.request, "urlopen", side_effect=err):
            assert post_statusline("h", 8080, {"session_id": "s"}) is False

    def test_post_url_error_returns_false(self) -> None:
        err = urllib.error.URLError("connection refused")
        with patch.object(aps.urllib.request, "urlopen", side_effect=err):
            assert post_statusline("h", 8080, {"session_id": "s"}) is False


class TestMergeAgentpulseSeed:
    def _resp(self, body: dict) -> MagicMock:
        cm = MagicMock()
        resp = MagicMock()
        resp.read = MagicMock(return_value=json.dumps(body).encode("utf-8"))
        cm.__enter__ = MagicMock(return_value=resp)
        cm.__exit__ = MagicMock(return_value=False)
        return cm

    def test_404_returns_ok_unmerged(self) -> None:
        err = urllib.error.HTTPError("u", 404, "no", {}, None)
        with patch.object(aps.urllib.request, "urlopen", side_effect=err):
            acc = SessionAccumulator()
            res = merge_agentpulse_seed(acc, "h", 8080, "sess")
            assert res.ok is True
            assert res.merged is False

    def test_5xx_returns_not_ok(self) -> None:
        err = urllib.error.HTTPError("u", 503, "down", {}, None)
        with patch.object(aps.urllib.request, "urlopen", side_effect=err):
            res = merge_agentpulse_seed(SessionAccumulator(), "h", 8080, "sess")
            assert res.ok is False

    def test_url_error_returns_not_ok(self) -> None:
        err = urllib.error.URLError("refused")
        with patch.object(aps.urllib.request, "urlopen", side_effect=err):
            res = merge_agentpulse_seed(SessionAccumulator(), "h", 8080, "sess")
            assert res.ok is False

    def test_success_merges_totals(self) -> None:
        acc = SessionAccumulator()
        acc.total_cost_usd = 0.10
        acc.total_input_tokens = 100
        body = {
            "cost_usd": 5.0,
            "total_input_tokens": 1000,
            "total_output_tokens": 500,
            "model_name": "claude-opus",
        }
        with patch.object(aps.urllib.request, "urlopen", return_value=self._resp(body)):
            res = merge_agentpulse_seed(acc, "h", 8080, "sess")
        assert res.ok is True
        assert res.merged is True
        assert acc.total_cost_usd == pytest.approx(5.10)
        assert acc.total_input_tokens == 1100
        assert acc.total_output_tokens == 500
        assert acc.last_model_name == "claude-opus"
        assert acc.session_id == "sess"

    def test_non_dict_response_treated_as_no_data(self) -> None:
        cm = MagicMock()
        resp = MagicMock()
        resp.read = MagicMock(return_value=b'"just-a-string"')
        cm.__enter__ = MagicMock(return_value=resp)
        cm.__exit__ = MagicMock(return_value=False)
        with patch.object(aps.urllib.request, "urlopen", return_value=cm):
            res = merge_agentpulse_seed(SessionAccumulator(), "h", 8080, "s")
        assert res.ok is True
        assert res.merged is False

    def test_non_numeric_totals_returns_not_ok(self) -> None:
        body = {"cost_usd": "not-a-number"}
        with patch.object(aps.urllib.request, "urlopen", return_value=self._resp(body)):
            res = merge_agentpulse_seed(SessionAccumulator(), "h", 8080, "s")
        assert res.ok is False


class TestLoadAgentpulseEndpoint:
    def test_returns_none_when_no_config(self, tmp_path: Path) -> None:
        # Non-existent path
        assert load_agentpulse_endpoint(tmp_path / "missing.json") is None

    def test_returns_host_port_tuple(self, tmp_path: Path) -> None:
        cfg = tmp_path / "config.json"
        cfg.write_text(json.dumps({"host": "localhost", "port": 8765}))
        assert load_agentpulse_endpoint(cfg) == ("localhost", 8765)


class TestSeedResult:
    def test_slots_only(self) -> None:
        r = SeedResult(ok=True, merged=False)
        assert r.ok is True
        assert r.merged is False
