# Generated By: Claude Code (Claude Opus 4.7 (1M context))

"""Tests for agent_service.agentpulse_config (lifted module)."""

from __future__ import annotations

import json
from pathlib import Path

from agent_service.agentpulse_config import (
    AgentPulseConfig,
    load_agentpulse_config,
)


class TestLoadAgentpulseConfig:
    def test_missing_file_returns_none(self, tmp_path: Path) -> None:
        assert load_agentpulse_config(tmp_path / "absent.json") is None

    def test_malformed_json_returns_none(self, tmp_path: Path) -> None:
        cfg = tmp_path / "config.json"
        cfg.write_text("this is not json")
        assert load_agentpulse_config(cfg) is None

    def test_missing_host_returns_none(self, tmp_path: Path) -> None:
        cfg = tmp_path / "config.json"
        cfg.write_text(json.dumps({"port": 8080}))
        assert load_agentpulse_config(cfg) is None

    def test_missing_port_returns_none(self, tmp_path: Path) -> None:
        cfg = tmp_path / "config.json"
        cfg.write_text(json.dumps({"host": "localhost"}))
        assert load_agentpulse_config(cfg) is None

    def test_valid_config_returns_dataclass(self, tmp_path: Path) -> None:
        cfg = tmp_path / "config.json"
        cfg.write_text(
            json.dumps({"host": "localhost", "port": 9999, "fetch_limits": False})
        )
        result = load_agentpulse_config(cfg)
        assert isinstance(result, AgentPulseConfig)
        assert result.host == "localhost"
        assert result.port == 9999
        assert result.fetch_limits is False

    def test_fetch_limits_defaults_true(self, tmp_path: Path) -> None:
        cfg = tmp_path / "config.json"
        cfg.write_text(json.dumps({"host": "h", "port": 1}))
        result = load_agentpulse_config(cfg)
        assert result is not None
        assert result.fetch_limits is True
