# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for agent_service.config."""

from pathlib import Path

import pydantic
import pytest
import yaml

from agent_service.config import AgentServiceConfig, load_config


def _valid_data(tmp_path: Path) -> dict:
    """Return a valid config data dict."""
    return {
        "agent_working_dir": str(tmp_path / "agent"),
        "tls_cert": str(tmp_path / "cert.pem"),
        "tls_key": str(tmp_path / "key.pem"),
        "tls_ca": str(tmp_path / "ca.pem"),
        "oidc_issuer": "https://github.com",
        "oidc_audience": "my-app",
        "authorized_subjects": ["user1", "user2"],
        "replay_buffer_size": 1000,
        "session_resume_on_startup": False,
        "listen_address": "0.0.0.0:8443",
    }


def _write_config(path: Path, data: dict) -> Path:
    """Write a YAML config file and return its path."""
    config_file = path / "config.yaml"
    config_file.write_text(yaml.dump(data))
    return config_file


class TestAgentServiceConfig:
    """Tests for the AgentServiceConfig model."""

    def test_valid_config_all_fields(self, tmp_path: Path) -> None:
        """All required fields present produces a valid config."""
        data = _valid_data(tmp_path=tmp_path)
        config = AgentServiceConfig(**data)
        assert config.listen_address == "0.0.0.0:8443"
        assert config.replay_buffer_size == 1000
        assert len(config.authorized_subjects) == 2

    def test_missing_required_field_raises(self) -> None:
        """Missing a required field raises ValidationError."""
        with pytest.raises(pydantic.ValidationError):
            AgentServiceConfig(
                agent_working_dir="/tmp/agent",
            )

    def test_extra_field_raises(self, tmp_path: Path) -> None:
        """Extra fields in config are rejected."""
        data = _valid_data(tmp_path=tmp_path)
        data["unknown_field"] = "should fail"
        with pytest.raises(pydantic.ValidationError):
            AgentServiceConfig(**data)

    def test_replay_buffer_size_must_be_positive(self, tmp_path: Path) -> None:
        """replay_buffer_size must be > 0."""
        data = _valid_data(tmp_path=tmp_path)
        data["replay_buffer_size"] = 0
        with pytest.raises(pydantic.ValidationError):
            AgentServiceConfig(**data)

    def test_listen_address_must_be_host_port(self, tmp_path: Path) -> None:
        """listen_address must be host:port format."""
        data = _valid_data(tmp_path=tmp_path)
        data["listen_address"] = "not-a-valid-address"
        with pytest.raises(pydantic.ValidationError):
            AgentServiceConfig(**data)


class TestLoadConfig:
    """Tests for the load_config function."""

    def test_load_from_yaml(self, tmp_path: Path) -> None:
        """Loads config from a YAML file."""
        data = _valid_data(tmp_path=tmp_path)
        config_file = _write_config(path=tmp_path, data=data)
        config = load_config(config_path=config_file)
        assert config.replay_buffer_size == 1000
        assert config.session_resume_on_startup is False

    def test_env_var_override(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Environment variables override YAML values."""
        data = _valid_data(tmp_path=tmp_path)
        config_file = _write_config(path=tmp_path, data=data)
        monkeypatch.setenv("AGENT_SERVICE_REPLAY_BUFFER_SIZE", "2000")
        config = load_config(config_path=config_file)
        assert config.replay_buffer_size == 2000

    def test_env_var_override_authorized_subjects(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Comma-separated env var overrides authorized_subjects list."""
        data = _valid_data(tmp_path=tmp_path)
        config_file = _write_config(path=tmp_path, data=data)
        monkeypatch.setenv("AGENT_SERVICE_AUTHORIZED_SUBJECTS", "a,b,c")
        config = load_config(config_path=config_file)
        assert config.authorized_subjects == ["a", "b", "c"]

    def test_env_var_override_bool(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Boolean env var override works."""
        data = _valid_data(tmp_path=tmp_path)
        config_file = _write_config(path=tmp_path, data=data)
        monkeypatch.setenv("AGENT_SERVICE_SESSION_RESUME_ON_STARTUP", "true")
        config = load_config(config_path=config_file)
        assert config.session_resume_on_startup is True

    def test_missing_config_file_raises(self, tmp_path: Path) -> None:
        """Non-existent config file raises FileNotFoundError."""
        with pytest.raises(FileNotFoundError):
            load_config(config_path=tmp_path / "nonexistent.yaml")
