# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for agent REST endpoints."""

from pathlib import Path
from unittest.mock import AsyncMock

import pytest
from fastapi.testclient import TestClient

from agent_service.agent import AgentClient
from agent_service.app import create_app
from agent_service.auth import AuthContext, require_auth
from agent_service.config import AgentServiceConfig
from agent_service.metrics import create_metrics


@pytest.fixture
def test_config(tmp_path: Path) -> AgentServiceConfig:
    return AgentServiceConfig(
        agent_working_dir=tmp_path / "agent",
        tls_cert=tmp_path / "cert.pem",
        tls_key=tmp_path / "key.pem",
        tls_ca=tmp_path / "ca.pem",
        oidc_issuer="https://github.com",
        oidc_audience="test",
        authorized_subjects=["test-user"],
        replay_buffer_size=100,
        session_resume_on_startup=False,
        listen_address="0.0.0.0:8443",
    )


def _mock_auth() -> AuthContext:
    return AuthContext(subject="test-user", claims={"sub": "test-user"})


@pytest.fixture
def client(test_config: AgentServiceConfig, tmp_path: Path) -> TestClient:
    app = create_app(config=test_config)
    app.dependency_overrides[require_auth] = _mock_auth

    # Set up app.state with required components for agent routes
    metrics = create_metrics()
    app.state.metrics = metrics
    app.state.agent = AgentClient(
        working_dir=tmp_path / "agent",
        resume_on_startup=False,
        on_event=AsyncMock(),
        metrics=metrics,
        agent_id="test-agent",
    )
    return TestClient(app)


class TestGetAgent:
    """Tests for GET /agent."""

    def test_returns_agent_status(self, client: TestClient) -> None:
        response = client.get("/agent")
        assert response.status_code == 200
        data = response.json()
        assert data["agent_id"] == "test-agent"
        assert "session_id" in data
        assert "working_dir" in data
        assert "timestamp" in data

    def test_requires_auth(
        self, test_config: AgentServiceConfig, tmp_path: Path
    ) -> None:
        """Without auth override, returns 401."""
        from agent_service.auth import OIDCValidator

        app = create_app(config=test_config)
        metrics = create_metrics()
        app.state.metrics = metrics
        app.state.oidc_validator = OIDCValidator(
            issuer="https://github.com",
            audience="test",
            authorized_subjects=["test-user"],
        )
        app.state.agent = AgentClient(
            working_dir=tmp_path / "agent",
            resume_on_startup=False,
            on_event=AsyncMock(),
            metrics=metrics,
            agent_id="test-agent",
        )
        raw_client = TestClient(app)
        response = raw_client.get("/agent")
        assert response.status_code == 401


class TestClearAgent:
    """Tests for POST /agent/clear."""

    def test_clears_agent(self, client: TestClient) -> None:
        response = client.post("/agent/clear")
        assert response.status_code == 200
        assert response.json()["status"] == "cleared"
