# Generated By: Claude Code (Claude Opus 4.6)

"""Entry point for python -m agent_service."""

import argparse
import logging
import ssl
import sys
import types
from pathlib import Path

import uvicorn

from agent_service.app import create_app
from agent_service.config import load_config

EXIT_SUCCESS = 0
EXIT_ERROR = 1

LOG_FORMAT = "%(asctime)s %(levelname)s %(name)s: %(message)s"

logger = logging.getLogger("agent_service")


def _install_excepthook(*, logger: logging.Logger) -> None:
    def _hook(
        exc_type: type[BaseException],
        exc_value: BaseException,
        exc_tb: types.TracebackType | None,
    ) -> None:
        if issubclass(exc_type, KeyboardInterrupt):
            sys.__excepthook__(exc_type, exc_value, exc_tb)
            return
        logger.critical("uncaught exception", exc_info=(exc_type, exc_value, exc_tb))

    sys.excepthook = _hook


def _configure_logging(*, level: int, log_file: str | None) -> None:
    if log_file:
        Path(log_file).parent.mkdir(parents=True, exist_ok=True)
        handler = logging.FileHandler(log_file, mode="a", encoding="utf-8")
        handler.setFormatter(logging.Formatter(LOG_FORMAT))
        logging.basicConfig(level=level, handlers=[handler])
    else:
        logging.basicConfig(level=level, format=LOG_FORMAT, stream=sys.stderr)


def main() -> int:
    """Load config and run the service."""
    parser = argparse.ArgumentParser(prog="agent_service")
    parser.add_argument(
        "config",
        nargs="?",
        default="config.yaml",
        help="path to YAML config file (default: config.yaml)",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="enable debug-level logging",
    )
    parser.add_argument(
        "--quiet",
        "-q",
        action="store_true",
        help="suppress non-essential output (INFO logs)",
    )
    parser.add_argument(
        "--log-file",
        type=str,
        default=None,
        help="write logs to this file instead of stderr",
    )
    args = parser.parse_args()

    if args.log_file:
        args.log_file = str(Path(args.log_file).expanduser().resolve())

    if args.debug:
        level = logging.DEBUG
    elif args.quiet:
        level = logging.WARNING
    else:
        level = logging.INFO

    _configure_logging(level=level, log_file=args.log_file)
    _install_excepthook(logger=logger)

    try:
        config = load_config(config_path=Path(args.config))

        host, port_str = config.listen_address.rsplit(":", 1)
        port = int(port_str)

        app = create_app(config=config)

        uvicorn.run(
            app,
            host=host,
            port=port,
            ssl_certfile=str(config.tls_cert),
            ssl_keyfile=str(config.tls_key),
            ssl_ca_certs=str(config.tls_ca),
            ssl_cert_reqs=ssl.CERT_REQUIRED,
        )
    except Exception:
        logger.exception("fatal error during startup")
        return EXIT_ERROR
    return EXIT_SUCCESS


if __name__ == "__main__":
    sys.exit(main())
