# Generated By: Claude Code (Claude Opus 4.6)

"""Claude SDK agent wrapper.

Isolates the SDK from FastAPI. Communicates outward via on_event callback.
"""

import asyncio
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Awaitable, Callable

from agent_service.model import ServerMessage

logger = logging.getLogger(__name__)


class AgentClient:
    """Wraps Claude SDK ClaudeSDKClient for the agent service."""

    def __init__(
        self,
        *,
        working_dir: Path,
        resume_on_startup: bool,
        on_event: Callable[[ServerMessage], Awaitable[None]],
        metrics: Any,
        agent_id: str,
    ) -> None:
        self._working_dir = working_dir
        self._resume_on_startup = resume_on_startup
        self._on_event = on_event
        self._metrics = metrics
        self._agent_id = agent_id
        self._session_id: str | None = None
        self._client: Any = None
        self._lock: asyncio.Lock = asyncio.Lock()

    async def start(self) -> None:
        """Initialize SDK client. Resume or fresh session based on config."""
        await self._start_session()

    async def _start_session(self) -> None:
        """Create or resume a Claude SDK session."""
        # SDK initialization deferred — will integrate when wiring
        pass

    async def send_message(
        self,
        *,
        content: str,
        source: str | None = None,
    ) -> None:
        """Send a user message and stream the response.

        Messages are processed sequentially via lock.
        """
        async with self._lock:
            self._metrics.messages_total.labels(direction="inbound").inc()
            await self._process_message(content=content, source=source)

    async def _process_message(
        self,
        *,
        content: str,
        source: str | None = None,
    ) -> None:
        """Process a single message through the SDK.

        Streaming event handling:
        - StreamEvent (text delta) -> emit via on_event
        - AssistantMessage (tool use only, skip TextBlock)
        - ResultMessage -> emit completion
        """
        # SDK message processing deferred — will integrate when wiring
        pass

    async def stop(self) -> None:
        """Stop the agent client and clean up resources."""
        self._client = None
        self._session_id = None

    async def clear(self) -> None:
        """Clear agent context, start fresh session."""
        self._session_id = None
        self._client = None
        await self._start_session()

    @property
    def status(self) -> dict:
        """Agent status for GET /agent."""
        return {
            "agent_id": self._agent_id,
            "session_id": self._session_id,
            "working_dir": str(self._working_dir),
            "timestamp": datetime.now(tz=timezone.utc).isoformat(),
        }
