# Generated By: Claude Code (Claude Opus 4.7 (1M context))

"""Claude SDK agent wrapper.

Isolates the SDK from FastAPI. Communicates outward via on_event callback
that receives ``ServerMessage`` instances ready to be broadcast to all
WebSocket clients.

Streaming dispatch follows the python/agent-sdk.md pattern:
- ``StreamEvent`` text_delta → emit text event (single source of truth for text)
- ``AssistantMessage.ToolUseBlock`` → emit tool_use event (TextBlock skipped to
  avoid duplicating StreamEvent text)
- ``ResultMessage`` → record accumulator, update metrics, forward statusline,
  emit result event
- ``SystemMessage`` → log only

Token / cost accumulation mirrors the Claude Code CLI's process-scoped
statusline behaviour: counters keep climbing across ``/clear`` and session
resume; only a fresh process starts at zero.
"""

from __future__ import annotations

import asyncio
import logging
import os
import socket
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Awaitable, Callable

from claude_agent_sdk import (
    AssistantMessage,
    ClaudeAgentOptions,
    ClaudeSDKClient,
    PermissionResultAllow,
    PermissionResultDeny,
    ResultMessage,
    StreamEvent,
    SystemMessage,
    ToolPermissionContext,
    ToolUseBlock,
)

from agent_service.agentpulse_statusline import (
    SessionAccumulator,
    build_payload,
    extract_model_name,
    load_agentpulse_endpoint,
    merge_agentpulse_seed,
    post_statusline,
)
from agent_service.model import EventMessage, ErrorMessage, ServerMessage

logger = logging.getLogger(__name__)


async def _deny_unapproved(
    tool_name: str,
    tool_input: dict[str, Any],
    context: ToolPermissionContext,
) -> PermissionResultAllow | PermissionResultDeny:
    """Deny any tool call not covered by the working directory's allow rules.

    Permission evaluation order: hooks → deny rules → permission mode →
    allow rules → canUseTool callback. If a call reaches this callback it
    was not auto-approved by the agent's settings, so we deny it. Mirrors
    the personal-assistant-dashboard pattern.
    """
    logger.info("denying unapproved tool call: %s", tool_name)
    return PermissionResultDeny(
        behavior="deny",
        message=f"Tool '{tool_name}' is not in the allowed permissions list.",
        interrupt=False,
    )


class AgentClient:
    """Wraps Claude SDK ClaudeSDKClient for the agent service."""

    def __init__(
        self,
        *,
        working_dir: Path,
        resume_on_startup: bool,
        on_event: Callable[[ServerMessage], Awaitable[None]],
        metrics: Any,
        agent_id: str,
        chat_model: str | None = None,
        source_system: str | None = None,
    ) -> None:
        self._working_dir = working_dir
        self._resume_on_startup = resume_on_startup
        self._on_event = on_event
        self._metrics = metrics
        self._agent_id = agent_id
        self._chat_model = chat_model
        self._session_id: str | None = None
        self._client: ClaudeSDKClient | None = None
        self._lock: asyncio.Lock = asyncio.Lock()
        self._receive_task: asyncio.Task[None] | None = None

        # Per-process usage accumulator. Mirrors the Claude Code CLI: cost
        # and token totals accumulate across /clear and session resume,
        # only resetting when the service process exits.
        self._accumulator = SessionAccumulator()
        if chat_model:
            self._accumulator.last_model_name = chat_model
        self._accumulator_seeded = False
        self._agentpulse_outage_warned = False
        self._agentpulse_endpoint: tuple[str, int] | None = load_agentpulse_endpoint()
        if self._agentpulse_endpoint is None:
            logger.info("AgentPulse statusline forwarding disabled (no config)")

        self._pid = os.getpid()
        self._source_system = source_system or socket.gethostname()
        # Last main-agent AssistantMessage.usage; used as the per-turn
        # snapshot when ResultMessage arrives.
        self._last_assistant_usage: dict[str, Any] | None = None
        self._turn_started_at: float | None = None

    # -- lifecycle -----------------------------------------------------------

    async def start(self) -> None:
        """Initialize SDK client. Resume or fresh session based on config."""
        await self._connect(fresh=not self._resume_on_startup)

    async def _connect(self, *, fresh: bool) -> None:
        """Create and connect the SDK client."""
        resume = None if fresh else self._find_last_session(self._working_dir)
        logger.info("connecting SDK; resume=%s", resume or "(new)")
        options_kwargs: dict[str, Any] = {
            "permission_mode": "default",
            "can_use_tool": _deny_unapproved,
            "include_partial_messages": True,
            "cwd": self._working_dir,
            "resume": resume,
        }
        if self._chat_model:
            options_kwargs["model"] = self._chat_model
        options = ClaudeAgentOptions(**options_kwargs)
        self._client = ClaudeSDKClient(options=options)
        await self._client.connect()
        logger.info("SDK connected")

    @staticmethod
    def _find_last_session(cwd: Path) -> str | None:
        """Find the most recent session ID for the given working directory.

        Same algorithm as personal-assistant-dashboard: the SDK persists
        session JSONL files under ``~/.claude/projects/<project_key>/``;
        the latest by mtime is the session ID.
        """
        home = Path.home()
        project_key = str(cwd).replace("/", "-").replace("\\", "-").replace(":", "-")
        sessions_dir = home / ".claude" / "projects" / project_key
        if not sessions_dir.is_dir():
            return None
        jsonl_files = [f for f in sessions_dir.iterdir() if f.suffix == ".jsonl"]
        if not jsonl_files:
            return None
        latest = max(jsonl_files, key=lambda f: f.stat().st_mtime)
        return latest.stem

    async def stop(self) -> None:
        """Cancel the receive loop and disconnect the SDK."""
        if self._receive_task is not None and not self._receive_task.done():
            self._receive_task.cancel()
            try:
                await self._receive_task
            except (asyncio.CancelledError, Exception):
                pass
            self._receive_task = None
        if self._client is not None:
            try:
                await self._client.disconnect()
            except Exception:
                logger.exception("SDK disconnect failed")
            self._client = None
        self._session_id = None

    async def clear(self) -> None:
        """Clear agent context, start fresh session.

        The usage accumulator is intentionally preserved so cost/token
        totals keep climbing after ``/clear``, matching the Claude Code
        CLI's statusline behaviour. The per-turn snapshot is reset so
        context % drops to 0 until the new session's first turn.

        Holds ``_lock`` for the full lifecycle cycle so a concurrent
        ``send_message`` cannot resume against a half-disconnected client.
        """
        async with self._lock:
            self._accumulator.reset_snapshot()
            await self.stop()
            await self._connect(fresh=True)

    # -- messaging -----------------------------------------------------------

    async def send_message(
        self,
        *,
        content: str,
        source: str | None = None,
    ) -> None:
        """Send a user message to the SDK and ensure the receive loop runs.

        Messages are processed sequentially via lock — if two arrive close
        together they queue.
        """
        async with self._lock:
            self._metrics.messages_total.labels(direction="inbound").inc()
            await self._process_message(content=content, source=source)

    async def _process_message(
        self,
        *,
        content: str,
        source: str | None = None,
    ) -> None:
        """Forward to the SDK and start the receive loop if not running."""
        if self._client is None:
            await self._emit_error("agent not connected")
            return
        try:
            self._turn_started_at = asyncio.get_running_loop().time()
            await self._client.query(content)
        except Exception:
            logger.exception("SDK query failed")
            self._metrics.errors_total.labels(error_type="sdk_query").inc()
            await self._emit_error("failed to send message; see logs")
            return
        if self._receive_task is None or self._receive_task.done():
            self._receive_task = asyncio.create_task(self._receive_loop())

    async def _receive_loop(self) -> None:
        """Consume messages from the SDK client and dispatch."""
        if self._client is None:
            return
        try:
            async for msg in self._client.receive_messages():
                await self._handle_message(msg)
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("receive loop error")
            self._metrics.errors_total.labels(error_type="receive_loop").inc()
            await self._emit_error("agent connection error; see logs")

    async def _handle_message(self, msg: Any) -> None:
        """Route an SDK message to the appropriate emit / record path."""
        if isinstance(msg, AssistantMessage):
            # Capture main-agent per-call usage for the turn snapshot.
            # Skip subagent messages — their context is not the main
            # conversation's current occupancy.
            if msg.usage and getattr(msg, "parent_tool_use_id", None) is None:
                self._last_assistant_usage = dict(msg.usage)
            # Text is already emitted via StreamEvent deltas — only handle
            # non-text blocks here to avoid duplication.
            for block in msg.content:
                if isinstance(block, ToolUseBlock):
                    self._metrics.tool_calls_total.inc()
                    await self._emit_event(
                        event_type="tool_use",
                        data={
                            "name": block.name,
                            "input": block.input,
                        },
                    )
        elif isinstance(msg, StreamEvent):
            event = msg.event
            if event.get("type") != "content_block_delta":
                return
            delta = event.get("delta") or {}
            if delta.get("type") != "text_delta":
                return
            text = delta.get("text", "")
            if text:
                await self._emit_event(
                    event_type="text_delta",
                    data={"text": text},
                )
        elif isinstance(msg, ResultMessage):
            await self._handle_result(msg)
        elif isinstance(msg, SystemMessage):
            logger.debug("system message: %s", msg)

    async def _handle_result(self, msg: ResultMessage) -> None:
        """Record accumulator, update metrics, forward statusline, emit event."""
        if msg.is_error:
            errors = getattr(msg, "errors", None) or []
            content = "; ".join(errors) if errors else "unknown agent error"
            self._metrics.errors_total.labels(error_type="result").inc()
            await self._emit_error(content)
            return

        # Update session ID (may have rotated)
        self._session_id = msg.session_id

        turn_snapshot = self._last_assistant_usage
        self._last_assistant_usage = None
        model_name = extract_model_name(msg.model_usage) or self._chat_model or ""

        # Update accumulator (cumulative)
        self._accumulator.record_result(
            session_id=msg.session_id,
            total_cost_usd=getattr(msg, "total_cost_usd", None),
            usage=dict(msg.usage) if msg.usage else None,
            duration_ms=getattr(msg, "duration_ms", 0) or 0,
            duration_api_ms=getattr(msg, "duration_api_ms", 0) or 0,
            model_name=model_name,
        )
        self._accumulator.record_turn_snapshot(turn_snapshot)

        # Per-turn token metrics (use the per-turn ResultMessage.usage so
        # counters reflect this turn's contribution, not lifetime totals).
        self._record_token_metrics(usage=msg.usage, model=model_name)

        # Active-time observation
        if self._turn_started_at is not None:
            duration = asyncio.get_running_loop().time() - self._turn_started_at
            self._metrics.agent_active_seconds.observe(duration)
            self._turn_started_at = None

        # Forward to AgentPulse asynchronously so a slow endpoint can't
        # block the receive loop.
        if self._agentpulse_endpoint is not None:
            asyncio.create_task(self._forward_statusline(msg.session_id))

        await self._emit_event(
            event_type="result",
            data={
                "session_id": msg.session_id,
                "total_cost_usd": getattr(msg, "total_cost_usd", None),
                "model": model_name,
            },
        )

    def _record_token_metrics(
        self, *, usage: dict[str, Any] | None, model: str
    ) -> None:
        """Increment tokens_total per direction with cache breakdown."""
        if not usage:
            return
        label_model = model or "unknown"
        for key, label in (
            ("input_tokens", "input"),
            ("output_tokens", "output"),
            ("cache_read_input_tokens", "cache_read"),
            ("cache_creation_input_tokens", "cache_creation"),
        ):
            value = int(usage.get(key) or 0)
            if value > 0:
                self._metrics.tokens_total.labels(
                    token_type=label, model=label_model
                ).inc(value)

    # -- statusline ----------------------------------------------------------

    async def _forward_statusline(self, session_id: str) -> None:
        """Seed-if-needed then POST a statusline payload (errors swallowed)."""
        assert self._agentpulse_endpoint is not None
        host, port = self._agentpulse_endpoint

        if not self._accumulator_seeded:
            seed = await asyncio.to_thread(
                merge_agentpulse_seed,
                self._accumulator,
                host,
                port,
                session_id,
            )
            if not seed.ok:
                if not self._agentpulse_outage_warned:
                    logger.warning(
                        "AgentPulse unreachable at %s:%d;"
                        " statusline forwarding deferred",
                        host,
                        port,
                    )
                    self._agentpulse_outage_warned = True
                return
            self._accumulator_seeded = True
            logger.info(
                "AgentPulse seeded session=%s merged=%s total_cost_usd=%.4f",
                session_id,
                seed.merged,
                self._accumulator.total_cost_usd,
            )

        payload = build_payload(
            self._accumulator,
            pid=self._pid,
            cwd=str(self._working_dir),
            source_system=self._source_system,
        )
        posted = await asyncio.to_thread(post_statusline, host, port, payload)
        if posted:
            self._agentpulse_outage_warned = False
        elif not self._agentpulse_outage_warned:
            logger.warning(
                "statusline POST failed for session=%s at %s:%d",
                session_id,
                host,
                port,
            )
            self._agentpulse_outage_warned = True

    # -- emit helpers --------------------------------------------------------

    async def _safe_emit(self, msg: ServerMessage) -> None:
        """Forward msg to on_event, swallowing transport-layer exceptions.

        Decouples transport reliability (e.g. ws_manager.broadcast) from the
        SDK receive loop's integrity. A failing client send must not silence
        all subsequent SDK output.
        """
        try:
            await self._on_event(msg)
        except Exception:
            logger.warning("on_event broadcast failed", exc_info=True)

    async def _emit_event(self, *, event_type: str, data: dict[str, Any]) -> None:
        """Build and broadcast an EventMessage. Sequence/timestamp are stamped
        by ws_manager.broadcast.
        """
        msg = EventMessage(
            type="event",
            agent_id=self._agent_id,
            session_id=self._session_id or "",
            sequence=0,
            timestamp="",
            event_type=event_type,
            data=data,
        )
        await self._safe_emit(msg)

    async def _emit_error(self, content: str) -> None:
        """Build and broadcast an ErrorMessage."""
        msg = ErrorMessage(
            type="error",
            agent_id=self._agent_id,
            session_id=self._session_id or "",
            sequence=0,
            timestamp="",
            content=content,
        )
        await self._safe_emit(msg)

    @property
    def status(self) -> dict:
        """Agent status for GET /agent."""
        return {
            "agent_id": self._agent_id,
            "session_id": self._session_id,
            "working_dir": str(self._working_dir),
            "model": self._accumulator.last_model_name or self._chat_model,
            "total_cost_usd": self._accumulator.total_cost_usd,
            "total_input_tokens": self._accumulator.total_input_tokens,
            "total_output_tokens": self._accumulator.total_output_tokens,
            "timestamp": datetime.now(tz=timezone.utc).isoformat(),
        }
