# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Shared AgentPulse config loader.

Lifted verbatim from personal-assistant-dashboard. To be replaced by a
shared `agentpulse-client` package — see issue tracked in
`.tmp-gh-issue-agentpulse-shared.md`. Once the shared package exists,
delete this module and update the import sites in
`agent_service/agent.py`.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

CONFIG_PATH = Path.home() / ".claude" / "agentpulse" / "config.json"

# Shared HTTP timeout for REST calls against the configured AgentPulse
# server. Used by both the bootstrap fetches and the statusline forwarder.
HTTP_TIMEOUT_S = 5


@dataclass(frozen=True)
class AgentPulseConfig:
    """Parsed AgentPulse config file."""

    host: str
    port: int
    fetch_limits: bool = True


def load_agentpulse_config(
    path: Path = CONFIG_PATH,
) -> AgentPulseConfig | None:
    """Read the AgentPulse config file.

    Returns ``None`` when the file is missing, malformed, or lacks the
    required host/port keys. ``fetch_limits`` defaults to True when
    absent.
    """
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.debug("AgentPulse config unreadable at %s: %s", path, exc)
        return None
    host = data.get("host")
    port = data.get("port")
    if not host or not port:
        logger.debug("AgentPulse config at %s missing host or port", path)
        return None
    return AgentPulseConfig(
        host=str(host),
        port=int(port),
        fetch_limits=bool(data.get("fetch_limits", True)),
    )
