# Generated By: Claude Code (Claude Opus 4.6)

"""FastAPI application factory."""

from contextlib import asynccontextmanager

from fastapi import FastAPI

from agent_service.agent import AgentClient
from agent_service.auth import OIDCValidator
from agent_service.config import AgentServiceConfig
from agent_service.metrics import create_metrics
from agent_service.routes.agent import router as agent_router
from agent_service.routes.health import router as health_router
from agent_service.routes.metrics import router as metrics_router
from agent_service.routes.ws import router as ws_router
from agent_service.ws_manager import WebSocketManager


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan — startup and shutdown."""
    config: AgentServiceConfig = app.state.config

    app.state.metrics = create_metrics()

    app.state.oidc_validator = OIDCValidator(
        issuer=config.oidc_issuer,
        audience=config.oidc_audience,
        authorized_subjects=config.authorized_subjects,
    )

    app.state.ws_manager = WebSocketManager(
        replay_buffer_size=config.replay_buffer_size,
        metrics=app.state.metrics,
    )

    app.state.agent = AgentClient(
        working_dir=config.agent_working_dir,
        resume_on_startup=config.session_resume_on_startup,
        on_event=lambda message: app.state.ws_manager.broadcast(message=message),
        metrics=app.state.metrics,
        agent_id=config.agent_working_dir.name,
        chat_model=config.chat_model,
        source_system=config.source_system,
    )
    await app.state.agent.start()

    yield

    # Shutdown
    await app.state.agent.stop()
    await app.state.ws_manager.close_all()


def create_app(*, config: AgentServiceConfig) -> FastAPI:
    """Create and configure the FastAPI application."""
    app = FastAPI(title="Agent Service", lifespan=lifespan)
    app.state.config = config
    app.include_router(health_router)
    app.include_router(metrics_router)
    app.include_router(agent_router)
    app.include_router(ws_router)
    return app
