# Generated By: Claude Code (Claude Opus 4.6)

"""Authentication and authorization for the agent service.

mTLS provides channel-level trust. OIDC provides user-level identity.
"""

import asyncio
import logging
from dataclasses import dataclass, field
from typing import Any

import jwt
from fastapi import HTTPException, Request, WebSocket, status

logger = logging.getLogger(__name__)


@dataclass
class AuthContext:
    """Authenticated user context passed to route handlers."""

    subject: str
    claims: dict = field(default_factory=dict)


class OIDCValidator:
    """Validates OIDC ID tokens against a JWKS endpoint."""

    def __init__(
        self,
        *,
        issuer: str,
        audience: str,
        authorized_subjects: list[str],
    ) -> None:
        self._issuer = issuer
        self._audience = audience
        self._authorized_subjects = set(authorized_subjects)
        self._jwks_client: jwt.PyJWKClient | None = None

    def _get_jwks_client(self) -> jwt.PyJWKClient:
        if self._jwks_client is None:
            jwks_url = f"{self._issuer.rstrip('/')}/.well-known/jwks.json"
            self._jwks_client = jwt.PyJWKClient(uri=jwks_url)
        return self._jwks_client

    async def _get_signing_key(self, *, token: str) -> Any:
        """Get the signing key for a token from JWKS.

        PyJWKClient.get_signing_key_from_jwt is synchronous (uses urllib).
        Run in a thread to avoid blocking the event loop.
        """
        client = self._get_jwks_client()
        signing_key = await asyncio.to_thread(client.get_signing_key_from_jwt, token)
        return signing_key.key

    async def validate_token(self, *, token: str) -> AuthContext:
        """Validate an OIDC ID token and return auth context.

        Checks: signature (via JWKS), issuer, audience, expiration,
        and subject against the authorized allowlist.
        """
        signing_key = await self._get_signing_key(token=token)
        claims = jwt.decode(
            jwt=token,
            key=signing_key,
            algorithms=["RS256"],
            audience=self._audience,
            issuer=self._issuer,
        )
        subject = claims.get("sub", "")
        if subject not in self._authorized_subjects:
            raise PermissionError(f"Subject '{subject}' is not authorized")
        return AuthContext(subject=subject, claims=claims)


def _extract_bearer_token(*, authorization: str | None) -> str:
    """Extract bearer token from Authorization header."""
    if not authorization:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing Authorization header",
        )
    parts = authorization.split(" ", 1)
    if len(parts) != 2 or parts[0].lower() != "bearer":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid Authorization header format",
        )
    return parts[1]


async def _do_auth(
    *, validator: OIDCValidator, metrics: Any, token: str
) -> AuthContext:
    """Shared auth logic for REST and WebSocket endpoints.

    Maps PermissionError (authenticated but subject not in the allowlist)
    to HTTP 403 Forbidden. All other auth failures map to HTTP 401
    Unauthorized. Raw exception messages are not leaked to callers.
    """
    try:
        context = await validator.validate_token(token=token)
        metrics.auth_attempts_total.labels(result="success").inc()
        return context
    except PermissionError as exc:
        metrics.auth_attempts_total.labels(result="forbidden").inc()
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Forbidden",
        ) from exc
    except Exception as exc:
        metrics.auth_attempts_total.labels(result="failure").inc()
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication failed",
        ) from exc


async def require_auth(request: Request) -> AuthContext:
    """FastAPI dependency for authenticated REST endpoints."""
    return await _do_auth(
        validator=request.app.state.oidc_validator,
        metrics=request.app.state.metrics,
        token=_extract_bearer_token(authorization=request.headers.get("authorization")),
    )


async def require_auth_ws(websocket: WebSocket) -> AuthContext:
    """FastAPI dependency for WebSocket upgrade auth."""
    return await _do_auth(
        validator=websocket.app.state.oidc_validator,
        metrics=websocket.app.state.metrics,
        token=_extract_bearer_token(
            authorization=websocket.headers.get("authorization")
        ),
    )
