# Generated By: Claude Code (Claude Opus 4.6)

"""Configuration loading and validation for the agent service."""

import logging
import os
from pathlib import Path

import yaml
from pydantic import BaseModel, ConfigDict, Field, field_validator

logger = logging.getLogger(__name__)


class AgentServiceConfig(BaseModel):
    """Agent service configuration. All fields are required — no defaults."""

    model_config = ConfigDict(extra="forbid")

    agent_working_dir: Path
    tls_cert: Path
    tls_key: Path
    tls_ca: Path
    oidc_issuer: str
    oidc_audience: str
    authorized_subjects: list[str]
    replay_buffer_size: int = Field(gt=0)
    session_resume_on_startup: bool
    listen_address: str
    # Optional model pin. When unset, the SDK CLI's configured default is used
    # (matches python/agent-sdk.md guidance). When set, pinned for every turn.
    # Will become wirable via REST eventually.
    chat_model: str | None = None
    # Optional source_system identifier emitted in AgentPulse statusline payloads.
    # When unset, defaults to socket.gethostname(). Override for container/cloud
    # deployments where the hostname is an opaque pod ID.
    source_system: str | None = None

    @field_validator("listen_address")
    @classmethod
    def validate_listen_address(cls, value: str) -> str:
        """Validate listen_address is host:port format."""
        parts = value.rsplit(":", 1)
        if len(parts) != 2:
            raise ValueError("listen_address must be host:port format")
        try:
            port = int(parts[1])
        except ValueError:
            raise ValueError("listen_address port must be an integer")
        if not 1 <= port <= 65535:
            raise ValueError("listen_address port must be 1-65535")
        return value


# Fields that are comma-separated lists when provided as env vars.
_LIST_FIELDS = {"authorized_subjects"}

# Fields that need type coercion from string env vars.
_INT_FIELDS = {"replay_buffer_size"}
_BOOL_FIELDS = {"session_resume_on_startup"}


def load_config(*, config_path: Path) -> AgentServiceConfig:
    """Load config from YAML file with environment variable overrides.

    Env vars are named AGENT_SERVICE_{FIELD_UPPER} and override YAML values.
    For list fields (authorized_subjects), the env var is comma-separated.
    """
    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")

    with open(config_path) as f:
        data = yaml.safe_load(f) or {}

    # Apply env var overrides
    for field_name in AgentServiceConfig.model_fields:
        env_key = f"AGENT_SERVICE_{field_name.upper()}"
        env_value = os.environ.get(env_key)
        if env_value is not None:
            if field_name in _LIST_FIELDS:
                data[field_name] = [item.strip() for item in env_value.split(",")]
            elif field_name in _INT_FIELDS:
                data[field_name] = int(env_value)
            elif field_name in _BOOL_FIELDS:
                data[field_name] = env_value.lower() in ("true", "1", "yes")
            else:
                data[field_name] = env_value

    return AgentServiceConfig(**data)
