# Generated By: Claude Code (Claude Opus 4.6)

"""Prometheus metric definitions for the agent service."""

import logging
from dataclasses import dataclass

from prometheus_client import (
    CollectorRegistry,
    Counter,
    Gauge,
    Histogram,
    Summary,
)

logger = logging.getLogger(__name__)


@dataclass
class Metrics:
    """Container for all service metrics."""

    registry: CollectorRegistry
    tokens_total: Counter
    messages_total: Counter
    tool_calls_total: Counter
    agent_active_seconds: Summary
    ws_connections: Gauge
    ws_connection_duration: Histogram
    auth_attempts_total: Counter
    errors_total: Counter


def create_metrics(*, registry: CollectorRegistry | None = None) -> Metrics:
    """Create all metrics, optionally with a custom registry for testing."""
    reg = registry or CollectorRegistry()

    return Metrics(
        registry=reg,
        tokens_total=Counter(
            "agent_tokens_total",
            "Token consumption (token_type: input, output, cache_read, cache_creation)",
            ["token_type", "model"],
            registry=reg,
        ),
        messages_total=Counter(
            "agent_messages_total",
            "Messages processed",
            ["direction"],
            registry=reg,
        ),
        tool_calls_total=Counter(
            "agent_tool_calls_total",
            "Tool calls made",
            registry=reg,
        ),
        agent_active_seconds=Summary(
            "agent_active_seconds",
            "Time agent spent active",
            registry=reg,
        ),
        ws_connections=Gauge(
            "ws_connections_active",
            "Active WebSocket connections",
            registry=reg,
        ),
        ws_connection_duration=Histogram(
            "ws_connection_duration_seconds",
            "WebSocket connection duration",
            registry=reg,
        ),
        auth_attempts_total=Counter(
            "auth_attempts_total",
            "Authentication attempts",
            ["result"],
            registry=reg,
        ),
        errors_total=Counter(
            "agent_errors_total",
            "Errors by type",
            ["error_type"],
            registry=reg,
        ),
    )
