# Generated By: Claude Code (Claude Opus 4.6)

"""Protocol message types for the agent service.

Server-to-client messages use extra="allow" (open schema).
Clients must tolerate unknown fields.
"""

import logging
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict

logger = logging.getLogger(__name__)


class ServerMessage(BaseModel):
    """Base server-to-client message. All server messages inherit from this."""

    model_config = ConfigDict(extra="allow")

    type: str
    agent_id: str
    session_id: str
    sequence: int
    timestamp: str  # ISO 8601


class EventMessage(ServerMessage):
    """Agent lifecycle event (PreToolUse, PostToolUse, etc.)."""

    event_type: str
    data: dict[str, Any]


class ErrorMessage(ServerMessage):
    """Error notification from the agent."""

    content: str


class ClientMessage(BaseModel):
    """Client-to-server message."""

    type: Literal["message"]
    content: str
    source: str | None = None


class ReplayRequest(BaseModel):
    """Client-to-server replay request (first message only)."""

    type: Literal["replay"]
    since: int | str  # Sequence number or ISO 8601 timestamp
