# Generated By: Claude Code (Claude Opus 4.6)

"""WebSocket connection manager with fan-out and replay buffer."""

import asyncio
import logging
from collections import deque
from datetime import datetime, timezone
from typing import Any

from agent_service.model import ServerMessage

logger = logging.getLogger(__name__)


class WebSocketManager:
    """Manages WebSocket connections, broadcasts events, and handles replay."""

    def __init__(self, *, replay_buffer_size: int, metrics: Any) -> None:
        self._connections: set = set()
        self._buffer: deque[dict] = deque(maxlen=replay_buffer_size)
        self._sequence: int = 0
        self._lock: asyncio.Lock = asyncio.Lock()
        self._metrics = metrics

    async def connect(self, *, ws: Any) -> None:
        """Register a new WebSocket connection."""
        self._connections.add(ws)
        self._metrics.ws_connections.inc()

    async def disconnect(self, *, ws: Any) -> None:
        """Remove a WebSocket connection."""
        self._connections.discard(ws)
        self._metrics.ws_connections.dec()

    async def broadcast(self, *, message: ServerMessage) -> None:
        """Assign sequence/timestamp and send to all connected clients.

        Sends are serialized under the lock to prevent concurrent
        send_json calls on the same WebSocket connection.
        """
        async with self._lock:
            self._sequence += 1
            data = message.model_dump()
            data["sequence"] = self._sequence
            data["timestamp"] = datetime.now(tz=timezone.utc).isoformat()
            self._buffer.append(data)

            dead: list = []
            connections = list(self._connections)

        for ws in connections:
            try:
                await ws.send_json(data=data)
            except Exception:
                dead.append(ws)

        for ws in dead:
            await self.disconnect(ws=ws)

    async def replay(self, *, ws: Any, since: int | str) -> None:
        """Replay buffered events to a single client.

        since: sequence number (int) — replay events after that sequence.
               ISO 8601 timestamp (str) — replay events after that time.
        """
        async with self._lock:
            snapshot = list(self._buffer)

        for event in snapshot:
            if isinstance(since, int):
                if event["sequence"] <= since:
                    continue
            else:
                event_ts = datetime.fromisoformat(event["timestamp"])
                since_ts = datetime.fromisoformat(str(since))
                if event_ts <= since_ts:
                    continue
            await ws.send_json(data=event)

    async def close_all(self) -> None:
        """Close all connections. Used during shutdown."""
        for ws in list(self._connections):
            try:
                await ws.close()
            except Exception:
                pass
        self._connections.clear()

    @property
    def connection_count(self) -> int:
        """Number of active connections."""
        return len(self._connections)
