# Generated By: Claude Code (Claude Opus 4.6)

"""Agent management REST endpoints."""

from fastapi import APIRouter, Depends, Request

from agent_service.auth import AuthContext, require_auth

router = APIRouter(prefix="/agent")


def _get_agent(request: Request):
    """Dependency to get the agent client from app state."""
    return request.app.state.agent


@router.get("")
async def get_agent_status(
    *,
    auth: AuthContext = Depends(require_auth),
    request: Request,
) -> dict:
    """Get agent status and metadata."""
    agent = _get_agent(request=request)
    return agent.status


@router.post("/clear")
async def clear_agent(
    *,
    auth: AuthContext = Depends(require_auth),
    request: Request,
) -> dict:
    """Clear agent context and start a fresh session."""
    agent = _get_agent(request=request)
    await agent.clear()
    return {"status": "cleared"}
