# Generated By: Claude Code (Claude Opus 4.6)

"""Health check endpoint."""

from fastapi import APIRouter

router = APIRouter()


@router.get("/health")
async def health() -> dict:
    """Unauthenticated health check."""
    return {"status": "ok"}
