# Generated By: Claude Code (Claude Opus 4.6)

"""Prometheus metrics endpoint."""

from fastapi import APIRouter, Request, Response
from prometheus_client import generate_latest

router = APIRouter()


@router.get("/metrics")
async def metrics(request: Request) -> Response:
    """Unauthenticated Prometheus metrics."""
    registry = request.app.state.metrics.registry
    return Response(
        content=generate_latest(registry),
        media_type="text/plain; version=0.0.4; charset=utf-8",
    )
