# Generated By: Claude Code (Claude Opus 4.6)

"""WebSocket endpoint for streaming agent conversation."""

import logging
import time

from fastapi import APIRouter, Depends, WebSocket, WebSocketDisconnect

from agent_service.auth import AuthContext, require_auth_ws

logger = logging.getLogger(__name__)

router = APIRouter()


@router.websocket("/agent/ws")
async def agent_websocket(
    websocket: WebSocket,
    auth: AuthContext = Depends(require_auth_ws),
) -> None:
    """Streaming conversation channel.

    First message may be a replay request. Subsequent messages are
    forwarded to the agent for processing.
    """
    ws_manager = websocket.app.state.ws_manager
    agent = websocket.app.state.agent
    metrics = websocket.app.state.metrics

    await websocket.accept()
    await ws_manager.connect(ws=websocket)

    start_time = time.monotonic()
    first_message = True

    try:
        while True:
            data = await websocket.receive_json()
            msg_type = data.get("type")

            if first_message and msg_type == "replay":
                since = data.get("since")
                if since is None:
                    await websocket.send_json(
                        {"error": "replay requires 'since' field"}
                    )
                    first_message = False
                    continue
                await ws_manager.replay(ws=websocket, since=since)
                first_message = False
                continue

            first_message = False

            if msg_type == "replay":
                await websocket.send_json(
                    {"error": "replay only valid as first message"}
                )
                continue

            if msg_type == "message":
                content = data.get("content")
                if content is None:
                    await websocket.send_json(
                        {"error": "message requires 'content' field"}
                    )
                    continue
                await agent.send_message(
                    content=content,
                    source=data.get("source"),
                )
    except WebSocketDisconnect:
        pass
    finally:
        await ws_manager.disconnect(ws=websocket)
        duration = time.monotonic() - start_time
        metrics.ws_connection_duration.observe(duration)
