# Generated By: Claude Code (Claude Opus 4.6)

HOME_DIR := $(subst \,/,$(HOME))
LOG_FILE := $(HOME_DIR)/.agent-service/agent-service.log

.PHONY: run
run: $(PYTHON)  ## Start the agent service (use DEBUG=1 for debug logging)
	@echo "Logging to $(LOG_FILE)"
	$(PYTHON) -m agent_service $(if $(DEBUG),--debug) --log-file $(LOG_FILE)
