# Generated By: Claude Code (Claude Opus 4.6)
# Test and quality-check targets. Included by the root Makefile.

.PHONY: test-format test-lint test-typecheck test-unit test-unit-verbose test-coverage test-complexity test-mutation test-reachability

test-format: install-dev  ## Check formatting without modifying files
	$(PYTHON) -m black --check $(PACKAGE_NAME) tests

test-lint: install-dev  ## Lint with flake8
	$(PYTHON) -m flake8 --max-line-length=88 --extend-ignore=E203,W503 $(PACKAGE_NAME) tests

test-typecheck: install-dev  ## Type check with mypy
	$(PYTHON) -m mypy $(PACKAGE_NAME)

test-unit: install-dev  ## Run pytest
	$(PYTHON) -m pytest

test-unit-verbose: install-dev  ## Run pytest with verbose output
	$(PYTHON) -m pytest -v

test-coverage: install-dev  ## Run pytest with coverage (80% threshold)
	$(PYTHON) -m pytest --cov=$(PACKAGE_NAME) --cov-report=term --cov-fail-under=80

test-complexity: install-dev  ## Enforce cyclomatic complexity with xenon (opt-in)
	$(PYTHON) -m xenon $(PACKAGE_NAME) --max-absolute B --max-modules B --max-average A

test-mutation: install-dev  ## Run mutation testing locally (opt-in; not part of check)
	$(PYTHON) -m mutmut run --CI --paths-to-mutate "$(PACKAGE_NAME)"

test-reachability:  ## Verify all content files are reachable from entry points (stdlib-only; no venv needed)
	@echo "Checking document reachability..."
	$(PY_SYS) scripts/reachability.py --check
